/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-09-11")
public class DatasetVersionEntity implements org.apache.thrift.TBase<DatasetVersionEntity, DatasetVersionEntity._Fields>, java.io.Serializable, Cloneable, Comparable<DatasetVersionEntity> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DatasetVersionEntity");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField DATASET_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("datasetName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VERSION_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("versionNo", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PROVENANCE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("provenanceType", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField STORAGE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("storagePath", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField UPSTREAM_VERSION_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("upstreamVersionIds", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField DERIVATION_CONFIG_FIELD_DESC = new org.apache.thrift.protocol.TField("derivationConfig", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField SCHEMA_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("schemaJson", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField ROW_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("rowCount", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField SIZE_BYTES_FIELD_DESC = new org.apache.thrift.protocol.TField("sizeBytes", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField OPERATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("operator", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField CLIENT_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("clientIp", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField REMARK_FIELD_DESC = new org.apache.thrift.protocol.TField("remark", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField DELETED_FIELD_DESC = new org.apache.thrift.protocol.TField("deleted", org.apache.thrift.protocol.TType.BOOL, (short)15);
  private static final org.apache.thrift.protocol.TField JOB_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("jobState", org.apache.thrift.protocol.TType.I32, (short)16);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DatasetVersionEntityStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DatasetVersionEntityTupleSchemeFactory();

  public long id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String datasetName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String versionNo; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String provenanceType; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String storagePath; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String upstreamVersionIds; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String derivationConfig; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String schemaJson; // optional
  public long rowCount; // optional
  public long sizeBytes; // optional
  public long createTime; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String operator; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String clientIp; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String remark; // optional
  public boolean deleted; // required
  public int jobState; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    DATASET_NAME((short)2, "datasetName"),
    VERSION_NO((short)3, "versionNo"),
    PROVENANCE_TYPE((short)4, "provenanceType"),
    STORAGE_PATH((short)5, "storagePath"),
    UPSTREAM_VERSION_IDS((short)6, "upstreamVersionIds"),
    DERIVATION_CONFIG((short)7, "derivationConfig"),
    SCHEMA_JSON((short)8, "schemaJson"),
    ROW_COUNT((short)9, "rowCount"),
    SIZE_BYTES((short)10, "sizeBytes"),
    CREATE_TIME((short)11, "createTime"),
    OPERATOR((short)12, "operator"),
    CLIENT_IP((short)13, "clientIp"),
    REMARK((short)14, "remark"),
    DELETED((short)15, "deleted"),
    JOB_STATE((short)16, "jobState");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // DATASET_NAME
          return DATASET_NAME;
        case 3: // VERSION_NO
          return VERSION_NO;
        case 4: // PROVENANCE_TYPE
          return PROVENANCE_TYPE;
        case 5: // STORAGE_PATH
          return STORAGE_PATH;
        case 6: // UPSTREAM_VERSION_IDS
          return UPSTREAM_VERSION_IDS;
        case 7: // DERIVATION_CONFIG
          return DERIVATION_CONFIG;
        case 8: // SCHEMA_JSON
          return SCHEMA_JSON;
        case 9: // ROW_COUNT
          return ROW_COUNT;
        case 10: // SIZE_BYTES
          return SIZE_BYTES;
        case 11: // CREATE_TIME
          return CREATE_TIME;
        case 12: // OPERATOR
          return OPERATOR;
        case 13: // CLIENT_IP
          return CLIENT_IP;
        case 14: // REMARK
          return REMARK;
        case 15: // DELETED
          return DELETED;
        case 16: // JOB_STATE
          return JOB_STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ROWCOUNT_ISSET_ID = 1;
  private static final int __SIZEBYTES_ISSET_ID = 2;
  private static final int __CREATETIME_ISSET_ID = 3;
  private static final int __DELETED_ISSET_ID = 4;
  private static final int __JOBSTATE_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.UPSTREAM_VERSION_IDS,_Fields.DERIVATION_CONFIG,_Fields.SCHEMA_JSON,_Fields.ROW_COUNT,_Fields.SIZE_BYTES,_Fields.OPERATOR,_Fields.CLIENT_IP,_Fields.REMARK,_Fields.JOB_STATE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DATASET_NAME, new org.apache.thrift.meta_data.FieldMetaData("datasetName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_NO, new org.apache.thrift.meta_data.FieldMetaData("versionNo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROVENANCE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("provenanceType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STORAGE_PATH, new org.apache.thrift.meta_data.FieldMetaData("storagePath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UPSTREAM_VERSION_IDS, new org.apache.thrift.meta_data.FieldMetaData("upstreamVersionIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DERIVATION_CONFIG, new org.apache.thrift.meta_data.FieldMetaData("derivationConfig", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCHEMA_JSON, new org.apache.thrift.meta_data.FieldMetaData("schemaJson", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROW_COUNT, new org.apache.thrift.meta_data.FieldMetaData("rowCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SIZE_BYTES, new org.apache.thrift.meta_data.FieldMetaData("sizeBytes", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OPERATOR, new org.apache.thrift.meta_data.FieldMetaData("operator", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_IP, new org.apache.thrift.meta_data.FieldMetaData("clientIp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REMARK, new org.apache.thrift.meta_data.FieldMetaData("remark", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DELETED, new org.apache.thrift.meta_data.FieldMetaData("deleted", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.JOB_STATE, new org.apache.thrift.meta_data.FieldMetaData("jobState", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DatasetVersionEntity.class, metaDataMap);
  }

  public DatasetVersionEntity() {
  }

  public DatasetVersionEntity(
    long id,
    java.lang.String datasetName,
    java.lang.String versionNo,
    java.lang.String provenanceType,
    java.lang.String storagePath,
    long createTime,
    boolean deleted)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.datasetName = datasetName;
    this.versionNo = versionNo;
    this.provenanceType = provenanceType;
    this.storagePath = storagePath;
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    this.deleted = deleted;
    setDeletedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DatasetVersionEntity(DatasetVersionEntity other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetDatasetName()) {
      this.datasetName = other.datasetName;
    }
    if (other.isSetVersionNo()) {
      this.versionNo = other.versionNo;
    }
    if (other.isSetProvenanceType()) {
      this.provenanceType = other.provenanceType;
    }
    if (other.isSetStoragePath()) {
      this.storagePath = other.storagePath;
    }
    if (other.isSetUpstreamVersionIds()) {
      this.upstreamVersionIds = other.upstreamVersionIds;
    }
    if (other.isSetDerivationConfig()) {
      this.derivationConfig = other.derivationConfig;
    }
    if (other.isSetSchemaJson()) {
      this.schemaJson = other.schemaJson;
    }
    this.rowCount = other.rowCount;
    this.sizeBytes = other.sizeBytes;
    this.createTime = other.createTime;
    if (other.isSetOperator()) {
      this.operator = other.operator;
    }
    if (other.isSetClientIp()) {
      this.clientIp = other.clientIp;
    }
    if (other.isSetRemark()) {
      this.remark = other.remark;
    }
    this.deleted = other.deleted;
    this.jobState = other.jobState;
  }

  @Override
  public DatasetVersionEntity deepCopy() {
    return new DatasetVersionEntity(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.datasetName = null;
    this.versionNo = null;
    this.provenanceType = null;
    this.storagePath = null;
    this.upstreamVersionIds = null;
    this.derivationConfig = null;
    this.schemaJson = null;
    setRowCountIsSet(false);
    this.rowCount = 0;
    setSizeBytesIsSet(false);
    this.sizeBytes = 0;
    setCreateTimeIsSet(false);
    this.createTime = 0;
    this.operator = null;
    this.clientIp = null;
    this.remark = null;
    setDeletedIsSet(false);
    this.deleted = false;
    setJobStateIsSet(false);
    this.jobState = 0;
  }

  public long getId() {
    return this.id;
  }

  public DatasetVersionEntity setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDatasetName() {
    return this.datasetName;
  }

  public DatasetVersionEntity setDatasetName(@org.apache.thrift.annotation.Nullable java.lang.String datasetName) {
    this.datasetName = datasetName;
    return this;
  }

  public void unsetDatasetName() {
    this.datasetName = null;
  }

  /** Returns true if field datasetName is set (has been assigned a value) and false otherwise */
  public boolean isSetDatasetName() {
    return this.datasetName != null;
  }

  public void setDatasetNameIsSet(boolean value) {
    if (!value) {
      this.datasetName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getVersionNo() {
    return this.versionNo;
  }

  public DatasetVersionEntity setVersionNo(@org.apache.thrift.annotation.Nullable java.lang.String versionNo) {
    this.versionNo = versionNo;
    return this;
  }

  public void unsetVersionNo() {
    this.versionNo = null;
  }

  /** Returns true if field versionNo is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionNo() {
    return this.versionNo != null;
  }

  public void setVersionNoIsSet(boolean value) {
    if (!value) {
      this.versionNo = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProvenanceType() {
    return this.provenanceType;
  }

  public DatasetVersionEntity setProvenanceType(@org.apache.thrift.annotation.Nullable java.lang.String provenanceType) {
    this.provenanceType = provenanceType;
    return this;
  }

  public void unsetProvenanceType() {
    this.provenanceType = null;
  }

  /** Returns true if field provenanceType is set (has been assigned a value) and false otherwise */
  public boolean isSetProvenanceType() {
    return this.provenanceType != null;
  }

  public void setProvenanceTypeIsSet(boolean value) {
    if (!value) {
      this.provenanceType = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStoragePath() {
    return this.storagePath;
  }

  public DatasetVersionEntity setStoragePath(@org.apache.thrift.annotation.Nullable java.lang.String storagePath) {
    this.storagePath = storagePath;
    return this;
  }

  public void unsetStoragePath() {
    this.storagePath = null;
  }

  /** Returns true if field storagePath is set (has been assigned a value) and false otherwise */
  public boolean isSetStoragePath() {
    return this.storagePath != null;
  }

  public void setStoragePathIsSet(boolean value) {
    if (!value) {
      this.storagePath = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUpstreamVersionIds() {
    return this.upstreamVersionIds;
  }

  public DatasetVersionEntity setUpstreamVersionIds(@org.apache.thrift.annotation.Nullable java.lang.String upstreamVersionIds) {
    this.upstreamVersionIds = upstreamVersionIds;
    return this;
  }

  public void unsetUpstreamVersionIds() {
    this.upstreamVersionIds = null;
  }

  /** Returns true if field upstreamVersionIds is set (has been assigned a value) and false otherwise */
  public boolean isSetUpstreamVersionIds() {
    return this.upstreamVersionIds != null;
  }

  public void setUpstreamVersionIdsIsSet(boolean value) {
    if (!value) {
      this.upstreamVersionIds = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDerivationConfig() {
    return this.derivationConfig;
  }

  public DatasetVersionEntity setDerivationConfig(@org.apache.thrift.annotation.Nullable java.lang.String derivationConfig) {
    this.derivationConfig = derivationConfig;
    return this;
  }

  public void unsetDerivationConfig() {
    this.derivationConfig = null;
  }

  /** Returns true if field derivationConfig is set (has been assigned a value) and false otherwise */
  public boolean isSetDerivationConfig() {
    return this.derivationConfig != null;
  }

  public void setDerivationConfigIsSet(boolean value) {
    if (!value) {
      this.derivationConfig = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSchemaJson() {
    return this.schemaJson;
  }

  public DatasetVersionEntity setSchemaJson(@org.apache.thrift.annotation.Nullable java.lang.String schemaJson) {
    this.schemaJson = schemaJson;
    return this;
  }

  public void unsetSchemaJson() {
    this.schemaJson = null;
  }

  /** Returns true if field schemaJson is set (has been assigned a value) and false otherwise */
  public boolean isSetSchemaJson() {
    return this.schemaJson != null;
  }

  public void setSchemaJsonIsSet(boolean value) {
    if (!value) {
      this.schemaJson = null;
    }
  }

  public long getRowCount() {
    return this.rowCount;
  }

  public DatasetVersionEntity setRowCount(long rowCount) {
    this.rowCount = rowCount;
    setRowCountIsSet(true);
    return this;
  }

  public void unsetRowCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ROWCOUNT_ISSET_ID);
  }

  /** Returns true if field rowCount is set (has been assigned a value) and false otherwise */
  public boolean isSetRowCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ROWCOUNT_ISSET_ID);
  }

  public void setRowCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ROWCOUNT_ISSET_ID, value);
  }

  public long getSizeBytes() {
    return this.sizeBytes;
  }

  public DatasetVersionEntity setSizeBytes(long sizeBytes) {
    this.sizeBytes = sizeBytes;
    setSizeBytesIsSet(true);
    return this;
  }

  public void unsetSizeBytes() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SIZEBYTES_ISSET_ID);
  }

  /** Returns true if field sizeBytes is set (has been assigned a value) and false otherwise */
  public boolean isSetSizeBytes() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SIZEBYTES_ISSET_ID);
  }

  public void setSizeBytesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SIZEBYTES_ISSET_ID, value);
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public DatasetVersionEntity setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOperator() {
    return this.operator;
  }

  public DatasetVersionEntity setOperator(@org.apache.thrift.annotation.Nullable java.lang.String operator) {
    this.operator = operator;
    return this;
  }

  public void unsetOperator() {
    this.operator = null;
  }

  /** Returns true if field operator is set (has been assigned a value) and false otherwise */
  public boolean isSetOperator() {
    return this.operator != null;
  }

  public void setOperatorIsSet(boolean value) {
    if (!value) {
      this.operator = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClientIp() {
    return this.clientIp;
  }

  public DatasetVersionEntity setClientIp(@org.apache.thrift.annotation.Nullable java.lang.String clientIp) {
    this.clientIp = clientIp;
    return this;
  }

  public void unsetClientIp() {
    this.clientIp = null;
  }

  /** Returns true if field clientIp is set (has been assigned a value) and false otherwise */
  public boolean isSetClientIp() {
    return this.clientIp != null;
  }

  public void setClientIpIsSet(boolean value) {
    if (!value) {
      this.clientIp = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRemark() {
    return this.remark;
  }

  public DatasetVersionEntity setRemark(@org.apache.thrift.annotation.Nullable java.lang.String remark) {
    this.remark = remark;
    return this;
  }

  public void unsetRemark() {
    this.remark = null;
  }

  /** Returns true if field remark is set (has been assigned a value) and false otherwise */
  public boolean isSetRemark() {
    return this.remark != null;
  }

  public void setRemarkIsSet(boolean value) {
    if (!value) {
      this.remark = null;
    }
  }

  public boolean isDeleted() {
    return this.deleted;
  }

  public DatasetVersionEntity setDeleted(boolean deleted) {
    this.deleted = deleted;
    setDeletedIsSet(true);
    return this;
  }

  public void unsetDeleted() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DELETED_ISSET_ID);
  }

  /** Returns true if field deleted is set (has been assigned a value) and false otherwise */
  public boolean isSetDeleted() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DELETED_ISSET_ID);
  }

  public void setDeletedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DELETED_ISSET_ID, value);
  }

  public int getJobState() {
    return this.jobState;
  }

  public DatasetVersionEntity setJobState(int jobState) {
    this.jobState = jobState;
    setJobStateIsSet(true);
    return this;
  }

  public void unsetJobState() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __JOBSTATE_ISSET_ID);
  }

  /** Returns true if field jobState is set (has been assigned a value) and false otherwise */
  public boolean isSetJobState() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __JOBSTATE_ISSET_ID);
  }

  public void setJobStateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __JOBSTATE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case DATASET_NAME:
      if (value == null) {
        unsetDatasetName();
      } else {
        setDatasetName((java.lang.String)value);
      }
      break;

    case VERSION_NO:
      if (value == null) {
        unsetVersionNo();
      } else {
        setVersionNo((java.lang.String)value);
      }
      break;

    case PROVENANCE_TYPE:
      if (value == null) {
        unsetProvenanceType();
      } else {
        setProvenanceType((java.lang.String)value);
      }
      break;

    case STORAGE_PATH:
      if (value == null) {
        unsetStoragePath();
      } else {
        setStoragePath((java.lang.String)value);
      }
      break;

    case UPSTREAM_VERSION_IDS:
      if (value == null) {
        unsetUpstreamVersionIds();
      } else {
        setUpstreamVersionIds((java.lang.String)value);
      }
      break;

    case DERIVATION_CONFIG:
      if (value == null) {
        unsetDerivationConfig();
      } else {
        setDerivationConfig((java.lang.String)value);
      }
      break;

    case SCHEMA_JSON:
      if (value == null) {
        unsetSchemaJson();
      } else {
        setSchemaJson((java.lang.String)value);
      }
      break;

    case ROW_COUNT:
      if (value == null) {
        unsetRowCount();
      } else {
        setRowCount((java.lang.Long)value);
      }
      break;

    case SIZE_BYTES:
      if (value == null) {
        unsetSizeBytes();
      } else {
        setSizeBytes((java.lang.Long)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    case OPERATOR:
      if (value == null) {
        unsetOperator();
      } else {
        setOperator((java.lang.String)value);
      }
      break;

    case CLIENT_IP:
      if (value == null) {
        unsetClientIp();
      } else {
        setClientIp((java.lang.String)value);
      }
      break;

    case REMARK:
      if (value == null) {
        unsetRemark();
      } else {
        setRemark((java.lang.String)value);
      }
      break;

    case DELETED:
      if (value == null) {
        unsetDeleted();
      } else {
        setDeleted((java.lang.Boolean)value);
      }
      break;

    case JOB_STATE:
      if (value == null) {
        unsetJobState();
      } else {
        setJobState((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case DATASET_NAME:
      return getDatasetName();

    case VERSION_NO:
      return getVersionNo();

    case PROVENANCE_TYPE:
      return getProvenanceType();

    case STORAGE_PATH:
      return getStoragePath();

    case UPSTREAM_VERSION_IDS:
      return getUpstreamVersionIds();

    case DERIVATION_CONFIG:
      return getDerivationConfig();

    case SCHEMA_JSON:
      return getSchemaJson();

    case ROW_COUNT:
      return getRowCount();

    case SIZE_BYTES:
      return getSizeBytes();

    case CREATE_TIME:
      return getCreateTime();

    case OPERATOR:
      return getOperator();

    case CLIENT_IP:
      return getClientIp();

    case REMARK:
      return getRemark();

    case DELETED:
      return isDeleted();

    case JOB_STATE:
      return getJobState();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case DATASET_NAME:
      return isSetDatasetName();
    case VERSION_NO:
      return isSetVersionNo();
    case PROVENANCE_TYPE:
      return isSetProvenanceType();
    case STORAGE_PATH:
      return isSetStoragePath();
    case UPSTREAM_VERSION_IDS:
      return isSetUpstreamVersionIds();
    case DERIVATION_CONFIG:
      return isSetDerivationConfig();
    case SCHEMA_JSON:
      return isSetSchemaJson();
    case ROW_COUNT:
      return isSetRowCount();
    case SIZE_BYTES:
      return isSetSizeBytes();
    case CREATE_TIME:
      return isSetCreateTime();
    case OPERATOR:
      return isSetOperator();
    case CLIENT_IP:
      return isSetClientIp();
    case REMARK:
      return isSetRemark();
    case DELETED:
      return isSetDeleted();
    case JOB_STATE:
      return isSetJobState();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DatasetVersionEntity)
      return this.equals((DatasetVersionEntity)that);
    return false;
  }

  public boolean equals(DatasetVersionEntity that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_datasetName = true && this.isSetDatasetName();
    boolean that_present_datasetName = true && that.isSetDatasetName();
    if (this_present_datasetName || that_present_datasetName) {
      if (!(this_present_datasetName && that_present_datasetName))
        return false;
      if (!this.datasetName.equals(that.datasetName))
        return false;
    }

    boolean this_present_versionNo = true && this.isSetVersionNo();
    boolean that_present_versionNo = true && that.isSetVersionNo();
    if (this_present_versionNo || that_present_versionNo) {
      if (!(this_present_versionNo && that_present_versionNo))
        return false;
      if (!this.versionNo.equals(that.versionNo))
        return false;
    }

    boolean this_present_provenanceType = true && this.isSetProvenanceType();
    boolean that_present_provenanceType = true && that.isSetProvenanceType();
    if (this_present_provenanceType || that_present_provenanceType) {
      if (!(this_present_provenanceType && that_present_provenanceType))
        return false;
      if (!this.provenanceType.equals(that.provenanceType))
        return false;
    }

    boolean this_present_storagePath = true && this.isSetStoragePath();
    boolean that_present_storagePath = true && that.isSetStoragePath();
    if (this_present_storagePath || that_present_storagePath) {
      if (!(this_present_storagePath && that_present_storagePath))
        return false;
      if (!this.storagePath.equals(that.storagePath))
        return false;
    }

    boolean this_present_upstreamVersionIds = true && this.isSetUpstreamVersionIds();
    boolean that_present_upstreamVersionIds = true && that.isSetUpstreamVersionIds();
    if (this_present_upstreamVersionIds || that_present_upstreamVersionIds) {
      if (!(this_present_upstreamVersionIds && that_present_upstreamVersionIds))
        return false;
      if (!this.upstreamVersionIds.equals(that.upstreamVersionIds))
        return false;
    }

    boolean this_present_derivationConfig = true && this.isSetDerivationConfig();
    boolean that_present_derivationConfig = true && that.isSetDerivationConfig();
    if (this_present_derivationConfig || that_present_derivationConfig) {
      if (!(this_present_derivationConfig && that_present_derivationConfig))
        return false;
      if (!this.derivationConfig.equals(that.derivationConfig))
        return false;
    }

    boolean this_present_schemaJson = true && this.isSetSchemaJson();
    boolean that_present_schemaJson = true && that.isSetSchemaJson();
    if (this_present_schemaJson || that_present_schemaJson) {
      if (!(this_present_schemaJson && that_present_schemaJson))
        return false;
      if (!this.schemaJson.equals(that.schemaJson))
        return false;
    }

    boolean this_present_rowCount = true && this.isSetRowCount();
    boolean that_present_rowCount = true && that.isSetRowCount();
    if (this_present_rowCount || that_present_rowCount) {
      if (!(this_present_rowCount && that_present_rowCount))
        return false;
      if (this.rowCount != that.rowCount)
        return false;
    }

    boolean this_present_sizeBytes = true && this.isSetSizeBytes();
    boolean that_present_sizeBytes = true && that.isSetSizeBytes();
    if (this_present_sizeBytes || that_present_sizeBytes) {
      if (!(this_present_sizeBytes && that_present_sizeBytes))
        return false;
      if (this.sizeBytes != that.sizeBytes)
        return false;
    }

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_operator = true && this.isSetOperator();
    boolean that_present_operator = true && that.isSetOperator();
    if (this_present_operator || that_present_operator) {
      if (!(this_present_operator && that_present_operator))
        return false;
      if (!this.operator.equals(that.operator))
        return false;
    }

    boolean this_present_clientIp = true && this.isSetClientIp();
    boolean that_present_clientIp = true && that.isSetClientIp();
    if (this_present_clientIp || that_present_clientIp) {
      if (!(this_present_clientIp && that_present_clientIp))
        return false;
      if (!this.clientIp.equals(that.clientIp))
        return false;
    }

    boolean this_present_remark = true && this.isSetRemark();
    boolean that_present_remark = true && that.isSetRemark();
    if (this_present_remark || that_present_remark) {
      if (!(this_present_remark && that_present_remark))
        return false;
      if (!this.remark.equals(that.remark))
        return false;
    }

    boolean this_present_deleted = true;
    boolean that_present_deleted = true;
    if (this_present_deleted || that_present_deleted) {
      if (!(this_present_deleted && that_present_deleted))
        return false;
      if (this.deleted != that.deleted)
        return false;
    }

    boolean this_present_jobState = true && this.isSetJobState();
    boolean that_present_jobState = true && that.isSetJobState();
    if (this_present_jobState || that_present_jobState) {
      if (!(this_present_jobState && that_present_jobState))
        return false;
      if (this.jobState != that.jobState)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetDatasetName()) ? 131071 : 524287);
    if (isSetDatasetName())
      hashCode = hashCode * 8191 + datasetName.hashCode();

    hashCode = hashCode * 8191 + ((isSetVersionNo()) ? 131071 : 524287);
    if (isSetVersionNo())
      hashCode = hashCode * 8191 + versionNo.hashCode();

    hashCode = hashCode * 8191 + ((isSetProvenanceType()) ? 131071 : 524287);
    if (isSetProvenanceType())
      hashCode = hashCode * 8191 + provenanceType.hashCode();

    hashCode = hashCode * 8191 + ((isSetStoragePath()) ? 131071 : 524287);
    if (isSetStoragePath())
      hashCode = hashCode * 8191 + storagePath.hashCode();

    hashCode = hashCode * 8191 + ((isSetUpstreamVersionIds()) ? 131071 : 524287);
    if (isSetUpstreamVersionIds())
      hashCode = hashCode * 8191 + upstreamVersionIds.hashCode();

    hashCode = hashCode * 8191 + ((isSetDerivationConfig()) ? 131071 : 524287);
    if (isSetDerivationConfig())
      hashCode = hashCode * 8191 + derivationConfig.hashCode();

    hashCode = hashCode * 8191 + ((isSetSchemaJson()) ? 131071 : 524287);
    if (isSetSchemaJson())
      hashCode = hashCode * 8191 + schemaJson.hashCode();

    hashCode = hashCode * 8191 + ((isSetRowCount()) ? 131071 : 524287);
    if (isSetRowCount())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(rowCount);

    hashCode = hashCode * 8191 + ((isSetSizeBytes()) ? 131071 : 524287);
    if (isSetSizeBytes())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sizeBytes);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + ((isSetOperator()) ? 131071 : 524287);
    if (isSetOperator())
      hashCode = hashCode * 8191 + operator.hashCode();

    hashCode = hashCode * 8191 + ((isSetClientIp()) ? 131071 : 524287);
    if (isSetClientIp())
      hashCode = hashCode * 8191 + clientIp.hashCode();

    hashCode = hashCode * 8191 + ((isSetRemark()) ? 131071 : 524287);
    if (isSetRemark())
      hashCode = hashCode * 8191 + remark.hashCode();

    hashCode = hashCode * 8191 + ((deleted) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetJobState()) ? 131071 : 524287);
    if (isSetJobState())
      hashCode = hashCode * 8191 + jobState;

    return hashCode;
  }

  @Override
  public int compareTo(DatasetVersionEntity other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDatasetName(), other.isSetDatasetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatasetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datasetName, other.datasetName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVersionNo(), other.isSetVersionNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionNo, other.versionNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProvenanceType(), other.isSetProvenanceType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvenanceType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provenanceType, other.provenanceType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStoragePath(), other.isSetStoragePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStoragePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.storagePath, other.storagePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUpstreamVersionIds(), other.isSetUpstreamVersionIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpstreamVersionIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.upstreamVersionIds, other.upstreamVersionIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDerivationConfig(), other.isSetDerivationConfig());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDerivationConfig()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.derivationConfig, other.derivationConfig);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSchemaJson(), other.isSetSchemaJson());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSchemaJson()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.schemaJson, other.schemaJson);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRowCount(), other.isSetRowCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRowCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rowCount, other.rowCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSizeBytes(), other.isSetSizeBytes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSizeBytes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sizeBytes, other.sizeBytes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOperator(), other.isSetOperator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operator, other.operator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetClientIp(), other.isSetClientIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientIp, other.clientIp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRemark(), other.isSetRemark());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemark()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remark, other.remark);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDeleted(), other.isSetDeleted());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeleted()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deleted, other.deleted);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetJobState(), other.isSetJobState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJobState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jobState, other.jobState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DatasetVersionEntity(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("datasetName:");
    if (this.datasetName == null) {
      sb.append("null");
    } else {
      sb.append(this.datasetName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("versionNo:");
    if (this.versionNo == null) {
      sb.append("null");
    } else {
      sb.append(this.versionNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("provenanceType:");
    if (this.provenanceType == null) {
      sb.append("null");
    } else {
      sb.append(this.provenanceType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("storagePath:");
    if (this.storagePath == null) {
      sb.append("null");
    } else {
      sb.append(this.storagePath);
    }
    first = false;
    if (isSetUpstreamVersionIds()) {
      if (!first) sb.append(", ");
      sb.append("upstreamVersionIds:");
      if (this.upstreamVersionIds == null) {
        sb.append("null");
      } else {
        sb.append(this.upstreamVersionIds);
      }
      first = false;
    }
    if (isSetDerivationConfig()) {
      if (!first) sb.append(", ");
      sb.append("derivationConfig:");
      if (this.derivationConfig == null) {
        sb.append("null");
      } else {
        sb.append(this.derivationConfig);
      }
      first = false;
    }
    if (isSetSchemaJson()) {
      if (!first) sb.append(", ");
      sb.append("schemaJson:");
      if (this.schemaJson == null) {
        sb.append("null");
      } else {
        sb.append(this.schemaJson);
      }
      first = false;
    }
    if (isSetRowCount()) {
      if (!first) sb.append(", ");
      sb.append("rowCount:");
      sb.append(this.rowCount);
      first = false;
    }
    if (isSetSizeBytes()) {
      if (!first) sb.append(", ");
      sb.append("sizeBytes:");
      sb.append(this.sizeBytes);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    if (isSetOperator()) {
      if (!first) sb.append(", ");
      sb.append("operator:");
      if (this.operator == null) {
        sb.append("null");
      } else {
        sb.append(this.operator);
      }
      first = false;
    }
    if (isSetClientIp()) {
      if (!first) sb.append(", ");
      sb.append("clientIp:");
      if (this.clientIp == null) {
        sb.append("null");
      } else {
        sb.append(this.clientIp);
      }
      first = false;
    }
    if (isSetRemark()) {
      if (!first) sb.append(", ");
      sb.append("remark:");
      if (this.remark == null) {
        sb.append("null");
      } else {
        sb.append(this.remark);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("deleted:");
    sb.append(this.deleted);
    first = false;
    if (isSetJobState()) {
      if (!first) sb.append(", ");
      sb.append("jobState:");
      sb.append(this.jobState);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DatasetVersionEntityStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DatasetVersionEntityStandardScheme getScheme() {
      return new DatasetVersionEntityStandardScheme();
    }
  }

  private static class DatasetVersionEntityStandardScheme extends org.apache.thrift.scheme.StandardScheme<DatasetVersionEntity> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DatasetVersionEntity struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATASET_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.datasetName = iprot.readString();
              struct.setDatasetNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERSION_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.versionNo = iprot.readString();
              struct.setVersionNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PROVENANCE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.provenanceType = iprot.readString();
              struct.setProvenanceTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // STORAGE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.storagePath = iprot.readString();
              struct.setStoragePathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // UPSTREAM_VERSION_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.upstreamVersionIds = iprot.readString();
              struct.setUpstreamVersionIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DERIVATION_CONFIG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.derivationConfig = iprot.readString();
              struct.setDerivationConfigIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // SCHEMA_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.schemaJson = iprot.readString();
              struct.setSchemaJsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ROW_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.rowCount = iprot.readI64();
              struct.setRowCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SIZE_BYTES
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sizeBytes = iprot.readI64();
              struct.setSizeBytesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // OPERATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.operator = iprot.readString();
              struct.setOperatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // CLIENT_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientIp = iprot.readString();
              struct.setClientIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // REMARK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.remark = iprot.readString();
              struct.setRemarkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // DELETED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.deleted = iprot.readBool();
              struct.setDeletedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // JOB_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.jobState = iprot.readI32();
              struct.setJobStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DatasetVersionEntity struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.datasetName != null) {
        oprot.writeFieldBegin(DATASET_NAME_FIELD_DESC);
        oprot.writeString(struct.datasetName);
        oprot.writeFieldEnd();
      }
      if (struct.versionNo != null) {
        oprot.writeFieldBegin(VERSION_NO_FIELD_DESC);
        oprot.writeString(struct.versionNo);
        oprot.writeFieldEnd();
      }
      if (struct.provenanceType != null) {
        oprot.writeFieldBegin(PROVENANCE_TYPE_FIELD_DESC);
        oprot.writeString(struct.provenanceType);
        oprot.writeFieldEnd();
      }
      if (struct.storagePath != null) {
        oprot.writeFieldBegin(STORAGE_PATH_FIELD_DESC);
        oprot.writeString(struct.storagePath);
        oprot.writeFieldEnd();
      }
      if (struct.upstreamVersionIds != null) {
        if (struct.isSetUpstreamVersionIds()) {
          oprot.writeFieldBegin(UPSTREAM_VERSION_IDS_FIELD_DESC);
          oprot.writeString(struct.upstreamVersionIds);
          oprot.writeFieldEnd();
        }
      }
      if (struct.derivationConfig != null) {
        if (struct.isSetDerivationConfig()) {
          oprot.writeFieldBegin(DERIVATION_CONFIG_FIELD_DESC);
          oprot.writeString(struct.derivationConfig);
          oprot.writeFieldEnd();
        }
      }
      if (struct.schemaJson != null) {
        if (struct.isSetSchemaJson()) {
          oprot.writeFieldBegin(SCHEMA_JSON_FIELD_DESC);
          oprot.writeString(struct.schemaJson);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetRowCount()) {
        oprot.writeFieldBegin(ROW_COUNT_FIELD_DESC);
        oprot.writeI64(struct.rowCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSizeBytes()) {
        oprot.writeFieldBegin(SIZE_BYTES_FIELD_DESC);
        oprot.writeI64(struct.sizeBytes);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      if (struct.operator != null) {
        if (struct.isSetOperator()) {
          oprot.writeFieldBegin(OPERATOR_FIELD_DESC);
          oprot.writeString(struct.operator);
          oprot.writeFieldEnd();
        }
      }
      if (struct.clientIp != null) {
        if (struct.isSetClientIp()) {
          oprot.writeFieldBegin(CLIENT_IP_FIELD_DESC);
          oprot.writeString(struct.clientIp);
          oprot.writeFieldEnd();
        }
      }
      if (struct.remark != null) {
        if (struct.isSetRemark()) {
          oprot.writeFieldBegin(REMARK_FIELD_DESC);
          oprot.writeString(struct.remark);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(DELETED_FIELD_DESC);
      oprot.writeBool(struct.deleted);
      oprot.writeFieldEnd();
      if (struct.isSetJobState()) {
        oprot.writeFieldBegin(JOB_STATE_FIELD_DESC);
        oprot.writeI32(struct.jobState);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DatasetVersionEntityTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DatasetVersionEntityTupleScheme getScheme() {
      return new DatasetVersionEntityTupleScheme();
    }
  }

  private static class DatasetVersionEntityTupleScheme extends org.apache.thrift.scheme.TupleScheme<DatasetVersionEntity> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DatasetVersionEntity struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetDatasetName()) {
        optionals.set(1);
      }
      if (struct.isSetVersionNo()) {
        optionals.set(2);
      }
      if (struct.isSetProvenanceType()) {
        optionals.set(3);
      }
      if (struct.isSetStoragePath()) {
        optionals.set(4);
      }
      if (struct.isSetUpstreamVersionIds()) {
        optionals.set(5);
      }
      if (struct.isSetDerivationConfig()) {
        optionals.set(6);
      }
      if (struct.isSetSchemaJson()) {
        optionals.set(7);
      }
      if (struct.isSetRowCount()) {
        optionals.set(8);
      }
      if (struct.isSetSizeBytes()) {
        optionals.set(9);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(10);
      }
      if (struct.isSetOperator()) {
        optionals.set(11);
      }
      if (struct.isSetClientIp()) {
        optionals.set(12);
      }
      if (struct.isSetRemark()) {
        optionals.set(13);
      }
      if (struct.isSetDeleted()) {
        optionals.set(14);
      }
      if (struct.isSetJobState()) {
        optionals.set(15);
      }
      oprot.writeBitSet(optionals, 16);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetDatasetName()) {
        oprot.writeString(struct.datasetName);
      }
      if (struct.isSetVersionNo()) {
        oprot.writeString(struct.versionNo);
      }
      if (struct.isSetProvenanceType()) {
        oprot.writeString(struct.provenanceType);
      }
      if (struct.isSetStoragePath()) {
        oprot.writeString(struct.storagePath);
      }
      if (struct.isSetUpstreamVersionIds()) {
        oprot.writeString(struct.upstreamVersionIds);
      }
      if (struct.isSetDerivationConfig()) {
        oprot.writeString(struct.derivationConfig);
      }
      if (struct.isSetSchemaJson()) {
        oprot.writeString(struct.schemaJson);
      }
      if (struct.isSetRowCount()) {
        oprot.writeI64(struct.rowCount);
      }
      if (struct.isSetSizeBytes()) {
        oprot.writeI64(struct.sizeBytes);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetOperator()) {
        oprot.writeString(struct.operator);
      }
      if (struct.isSetClientIp()) {
        oprot.writeString(struct.clientIp);
      }
      if (struct.isSetRemark()) {
        oprot.writeString(struct.remark);
      }
      if (struct.isSetDeleted()) {
        oprot.writeBool(struct.deleted);
      }
      if (struct.isSetJobState()) {
        oprot.writeI32(struct.jobState);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DatasetVersionEntity struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(16);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.datasetName = iprot.readString();
        struct.setDatasetNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.versionNo = iprot.readString();
        struct.setVersionNoIsSet(true);
      }
      if (incoming.get(3)) {
        struct.provenanceType = iprot.readString();
        struct.setProvenanceTypeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.storagePath = iprot.readString();
        struct.setStoragePathIsSet(true);
      }
      if (incoming.get(5)) {
        struct.upstreamVersionIds = iprot.readString();
        struct.setUpstreamVersionIdsIsSet(true);
      }
      if (incoming.get(6)) {
        struct.derivationConfig = iprot.readString();
        struct.setDerivationConfigIsSet(true);
      }
      if (incoming.get(7)) {
        struct.schemaJson = iprot.readString();
        struct.setSchemaJsonIsSet(true);
      }
      if (incoming.get(8)) {
        struct.rowCount = iprot.readI64();
        struct.setRowCountIsSet(true);
      }
      if (incoming.get(9)) {
        struct.sizeBytes = iprot.readI64();
        struct.setSizeBytesIsSet(true);
      }
      if (incoming.get(10)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(11)) {
        struct.operator = iprot.readString();
        struct.setOperatorIsSet(true);
      }
      if (incoming.get(12)) {
        struct.clientIp = iprot.readString();
        struct.setClientIpIsSet(true);
      }
      if (incoming.get(13)) {
        struct.remark = iprot.readString();
        struct.setRemarkIsSet(true);
      }
      if (incoming.get(14)) {
        struct.deleted = iprot.readBool();
        struct.setDeletedIsSet(true);
      }
      if (incoming.get(15)) {
        struct.jobState = iprot.readI32();
        struct.setJobStateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

