/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-09-11")
public class LineageNode implements org.apache.thrift.TBase<LineageNode, LineageNode._Fields>, java.io.Serializable, Cloneable, Comparable<LineageNode> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LineageNode");

  private static final org.apache.thrift.protocol.TField VERSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("versionId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField DATASET_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("datasetName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VERSION_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("versionNo", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PROVENANCE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("provenanceType", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PROVENANCE_LABEL_FIELD_DESC = new org.apache.thrift.protocol.TField("provenanceLabel", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField STORAGE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("storagePath", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField OPERATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("operator", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField CLIENT_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("clientIp", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField REMARK_FIELD_DESC = new org.apache.thrift.protocol.TField("remark", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField DELETED_FIELD_DESC = new org.apache.thrift.protocol.TField("deleted", org.apache.thrift.protocol.TType.BOOL, (short)11);
  private static final org.apache.thrift.protocol.TField JOB_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("jobState", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField FOCUS_FIELD_DESC = new org.apache.thrift.protocol.TField("focus", org.apache.thrift.protocol.TType.BOOL, (short)13);
  private static final org.apache.thrift.protocol.TField DERIVATION_CONFIG_FIELD_DESC = new org.apache.thrift.protocol.TField("derivationConfig", org.apache.thrift.protocol.TType.STRING, (short)14);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LineageNodeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LineageNodeTupleSchemeFactory();

  public long versionId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String datasetName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String versionNo; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String provenanceType; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String provenanceLabel; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String storagePath; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String operator; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String clientIp; // optional
  public long createTime; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String remark; // optional
  public boolean deleted; // required
  public int jobState; // optional
  public boolean focus; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String derivationConfig; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VERSION_ID((short)1, "versionId"),
    DATASET_NAME((short)2, "datasetName"),
    VERSION_NO((short)3, "versionNo"),
    PROVENANCE_TYPE((short)4, "provenanceType"),
    PROVENANCE_LABEL((short)5, "provenanceLabel"),
    STORAGE_PATH((short)6, "storagePath"),
    OPERATOR((short)7, "operator"),
    CLIENT_IP((short)8, "clientIp"),
    CREATE_TIME((short)9, "createTime"),
    REMARK((short)10, "remark"),
    DELETED((short)11, "deleted"),
    JOB_STATE((short)12, "jobState"),
    FOCUS((short)13, "focus"),
    DERIVATION_CONFIG((short)14, "derivationConfig");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VERSION_ID
          return VERSION_ID;
        case 2: // DATASET_NAME
          return DATASET_NAME;
        case 3: // VERSION_NO
          return VERSION_NO;
        case 4: // PROVENANCE_TYPE
          return PROVENANCE_TYPE;
        case 5: // PROVENANCE_LABEL
          return PROVENANCE_LABEL;
        case 6: // STORAGE_PATH
          return STORAGE_PATH;
        case 7: // OPERATOR
          return OPERATOR;
        case 8: // CLIENT_IP
          return CLIENT_IP;
        case 9: // CREATE_TIME
          return CREATE_TIME;
        case 10: // REMARK
          return REMARK;
        case 11: // DELETED
          return DELETED;
        case 12: // JOB_STATE
          return JOB_STATE;
        case 13: // FOCUS
          return FOCUS;
        case 14: // DERIVATION_CONFIG
          return DERIVATION_CONFIG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERSIONID_ISSET_ID = 0;
  private static final int __CREATETIME_ISSET_ID = 1;
  private static final int __DELETED_ISSET_ID = 2;
  private static final int __JOBSTATE_ISSET_ID = 3;
  private static final int __FOCUS_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.PROVENANCE_TYPE,_Fields.PROVENANCE_LABEL,_Fields.STORAGE_PATH,_Fields.OPERATOR,_Fields.CLIENT_IP,_Fields.REMARK,_Fields.JOB_STATE,_Fields.DERIVATION_CONFIG};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VERSION_ID, new org.apache.thrift.meta_data.FieldMetaData("versionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DATASET_NAME, new org.apache.thrift.meta_data.FieldMetaData("datasetName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_NO, new org.apache.thrift.meta_data.FieldMetaData("versionNo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROVENANCE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("provenanceType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROVENANCE_LABEL, new org.apache.thrift.meta_data.FieldMetaData("provenanceLabel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STORAGE_PATH, new org.apache.thrift.meta_data.FieldMetaData("storagePath", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OPERATOR, new org.apache.thrift.meta_data.FieldMetaData("operator", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_IP, new org.apache.thrift.meta_data.FieldMetaData("clientIp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.REMARK, new org.apache.thrift.meta_data.FieldMetaData("remark", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DELETED, new org.apache.thrift.meta_data.FieldMetaData("deleted", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.JOB_STATE, new org.apache.thrift.meta_data.FieldMetaData("jobState", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FOCUS, new org.apache.thrift.meta_data.FieldMetaData("focus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.DERIVATION_CONFIG, new org.apache.thrift.meta_data.FieldMetaData("derivationConfig", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LineageNode.class, metaDataMap);
  }

  public LineageNode() {
  }

  public LineageNode(
    long versionId,
    java.lang.String datasetName,
    java.lang.String versionNo,
    long createTime,
    boolean deleted,
    boolean focus)
  {
    this();
    this.versionId = versionId;
    setVersionIdIsSet(true);
    this.datasetName = datasetName;
    this.versionNo = versionNo;
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    this.deleted = deleted;
    setDeletedIsSet(true);
    this.focus = focus;
    setFocusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LineageNode(LineageNode other) {
    __isset_bitfield = other.__isset_bitfield;
    this.versionId = other.versionId;
    if (other.isSetDatasetName()) {
      this.datasetName = other.datasetName;
    }
    if (other.isSetVersionNo()) {
      this.versionNo = other.versionNo;
    }
    if (other.isSetProvenanceType()) {
      this.provenanceType = other.provenanceType;
    }
    if (other.isSetProvenanceLabel()) {
      this.provenanceLabel = other.provenanceLabel;
    }
    if (other.isSetStoragePath()) {
      this.storagePath = other.storagePath;
    }
    if (other.isSetOperator()) {
      this.operator = other.operator;
    }
    if (other.isSetClientIp()) {
      this.clientIp = other.clientIp;
    }
    this.createTime = other.createTime;
    if (other.isSetRemark()) {
      this.remark = other.remark;
    }
    this.deleted = other.deleted;
    this.jobState = other.jobState;
    this.focus = other.focus;
    if (other.isSetDerivationConfig()) {
      this.derivationConfig = other.derivationConfig;
    }
  }

  @Override
  public LineageNode deepCopy() {
    return new LineageNode(this);
  }

  @Override
  public void clear() {
    setVersionIdIsSet(false);
    this.versionId = 0;
    this.datasetName = null;
    this.versionNo = null;
    this.provenanceType = null;
    this.provenanceLabel = null;
    this.storagePath = null;
    this.operator = null;
    this.clientIp = null;
    setCreateTimeIsSet(false);
    this.createTime = 0;
    this.remark = null;
    setDeletedIsSet(false);
    this.deleted = false;
    setJobStateIsSet(false);
    this.jobState = 0;
    setFocusIsSet(false);
    this.focus = false;
    this.derivationConfig = null;
  }

  public long getVersionId() {
    return this.versionId;
  }

  public LineageNode setVersionId(long versionId) {
    this.versionId = versionId;
    setVersionIdIsSet(true);
    return this;
  }

  public void unsetVersionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERSIONID_ISSET_ID);
  }

  /** Returns true if field versionId is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERSIONID_ISSET_ID);
  }

  public void setVersionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERSIONID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDatasetName() {
    return this.datasetName;
  }

  public LineageNode setDatasetName(@org.apache.thrift.annotation.Nullable java.lang.String datasetName) {
    this.datasetName = datasetName;
    return this;
  }

  public void unsetDatasetName() {
    this.datasetName = null;
  }

  /** Returns true if field datasetName is set (has been assigned a value) and false otherwise */
  public boolean isSetDatasetName() {
    return this.datasetName != null;
  }

  public void setDatasetNameIsSet(boolean value) {
    if (!value) {
      this.datasetName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getVersionNo() {
    return this.versionNo;
  }

  public LineageNode setVersionNo(@org.apache.thrift.annotation.Nullable java.lang.String versionNo) {
    this.versionNo = versionNo;
    return this;
  }

  public void unsetVersionNo() {
    this.versionNo = null;
  }

  /** Returns true if field versionNo is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionNo() {
    return this.versionNo != null;
  }

  public void setVersionNoIsSet(boolean value) {
    if (!value) {
      this.versionNo = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProvenanceType() {
    return this.provenanceType;
  }

  public LineageNode setProvenanceType(@org.apache.thrift.annotation.Nullable java.lang.String provenanceType) {
    this.provenanceType = provenanceType;
    return this;
  }

  public void unsetProvenanceType() {
    this.provenanceType = null;
  }

  /** Returns true if field provenanceType is set (has been assigned a value) and false otherwise */
  public boolean isSetProvenanceType() {
    return this.provenanceType != null;
  }

  public void setProvenanceTypeIsSet(boolean value) {
    if (!value) {
      this.provenanceType = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProvenanceLabel() {
    return this.provenanceLabel;
  }

  public LineageNode setProvenanceLabel(@org.apache.thrift.annotation.Nullable java.lang.String provenanceLabel) {
    this.provenanceLabel = provenanceLabel;
    return this;
  }

  public void unsetProvenanceLabel() {
    this.provenanceLabel = null;
  }

  /** Returns true if field provenanceLabel is set (has been assigned a value) and false otherwise */
  public boolean isSetProvenanceLabel() {
    return this.provenanceLabel != null;
  }

  public void setProvenanceLabelIsSet(boolean value) {
    if (!value) {
      this.provenanceLabel = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStoragePath() {
    return this.storagePath;
  }

  public LineageNode setStoragePath(@org.apache.thrift.annotation.Nullable java.lang.String storagePath) {
    this.storagePath = storagePath;
    return this;
  }

  public void unsetStoragePath() {
    this.storagePath = null;
  }

  /** Returns true if field storagePath is set (has been assigned a value) and false otherwise */
  public boolean isSetStoragePath() {
    return this.storagePath != null;
  }

  public void setStoragePathIsSet(boolean value) {
    if (!value) {
      this.storagePath = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOperator() {
    return this.operator;
  }

  public LineageNode setOperator(@org.apache.thrift.annotation.Nullable java.lang.String operator) {
    this.operator = operator;
    return this;
  }

  public void unsetOperator() {
    this.operator = null;
  }

  /** Returns true if field operator is set (has been assigned a value) and false otherwise */
  public boolean isSetOperator() {
    return this.operator != null;
  }

  public void setOperatorIsSet(boolean value) {
    if (!value) {
      this.operator = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClientIp() {
    return this.clientIp;
  }

  public LineageNode setClientIp(@org.apache.thrift.annotation.Nullable java.lang.String clientIp) {
    this.clientIp = clientIp;
    return this;
  }

  public void unsetClientIp() {
    this.clientIp = null;
  }

  /** Returns true if field clientIp is set (has been assigned a value) and false otherwise */
  public boolean isSetClientIp() {
    return this.clientIp != null;
  }

  public void setClientIpIsSet(boolean value) {
    if (!value) {
      this.clientIp = null;
    }
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public LineageNode setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRemark() {
    return this.remark;
  }

  public LineageNode setRemark(@org.apache.thrift.annotation.Nullable java.lang.String remark) {
    this.remark = remark;
    return this;
  }

  public void unsetRemark() {
    this.remark = null;
  }

  /** Returns true if field remark is set (has been assigned a value) and false otherwise */
  public boolean isSetRemark() {
    return this.remark != null;
  }

  public void setRemarkIsSet(boolean value) {
    if (!value) {
      this.remark = null;
    }
  }

  public boolean isDeleted() {
    return this.deleted;
  }

  public LineageNode setDeleted(boolean deleted) {
    this.deleted = deleted;
    setDeletedIsSet(true);
    return this;
  }

  public void unsetDeleted() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DELETED_ISSET_ID);
  }

  /** Returns true if field deleted is set (has been assigned a value) and false otherwise */
  public boolean isSetDeleted() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DELETED_ISSET_ID);
  }

  public void setDeletedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DELETED_ISSET_ID, value);
  }

  public int getJobState() {
    return this.jobState;
  }

  public LineageNode setJobState(int jobState) {
    this.jobState = jobState;
    setJobStateIsSet(true);
    return this;
  }

  public void unsetJobState() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __JOBSTATE_ISSET_ID);
  }

  /** Returns true if field jobState is set (has been assigned a value) and false otherwise */
  public boolean isSetJobState() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __JOBSTATE_ISSET_ID);
  }

  public void setJobStateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __JOBSTATE_ISSET_ID, value);
  }

  public boolean isFocus() {
    return this.focus;
  }

  public LineageNode setFocus(boolean focus) {
    this.focus = focus;
    setFocusIsSet(true);
    return this;
  }

  public void unsetFocus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FOCUS_ISSET_ID);
  }

  /** Returns true if field focus is set (has been assigned a value) and false otherwise */
  public boolean isSetFocus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FOCUS_ISSET_ID);
  }

  public void setFocusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FOCUS_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDerivationConfig() {
    return this.derivationConfig;
  }

  public LineageNode setDerivationConfig(@org.apache.thrift.annotation.Nullable java.lang.String derivationConfig) {
    this.derivationConfig = derivationConfig;
    return this;
  }

  public void unsetDerivationConfig() {
    this.derivationConfig = null;
  }

  /** Returns true if field derivationConfig is set (has been assigned a value) and false otherwise */
  public boolean isSetDerivationConfig() {
    return this.derivationConfig != null;
  }

  public void setDerivationConfigIsSet(boolean value) {
    if (!value) {
      this.derivationConfig = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case VERSION_ID:
      if (value == null) {
        unsetVersionId();
      } else {
        setVersionId((java.lang.Long)value);
      }
      break;

    case DATASET_NAME:
      if (value == null) {
        unsetDatasetName();
      } else {
        setDatasetName((java.lang.String)value);
      }
      break;

    case VERSION_NO:
      if (value == null) {
        unsetVersionNo();
      } else {
        setVersionNo((java.lang.String)value);
      }
      break;

    case PROVENANCE_TYPE:
      if (value == null) {
        unsetProvenanceType();
      } else {
        setProvenanceType((java.lang.String)value);
      }
      break;

    case PROVENANCE_LABEL:
      if (value == null) {
        unsetProvenanceLabel();
      } else {
        setProvenanceLabel((java.lang.String)value);
      }
      break;

    case STORAGE_PATH:
      if (value == null) {
        unsetStoragePath();
      } else {
        setStoragePath((java.lang.String)value);
      }
      break;

    case OPERATOR:
      if (value == null) {
        unsetOperator();
      } else {
        setOperator((java.lang.String)value);
      }
      break;

    case CLIENT_IP:
      if (value == null) {
        unsetClientIp();
      } else {
        setClientIp((java.lang.String)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    case REMARK:
      if (value == null) {
        unsetRemark();
      } else {
        setRemark((java.lang.String)value);
      }
      break;

    case DELETED:
      if (value == null) {
        unsetDeleted();
      } else {
        setDeleted((java.lang.Boolean)value);
      }
      break;

    case JOB_STATE:
      if (value == null) {
        unsetJobState();
      } else {
        setJobState((java.lang.Integer)value);
      }
      break;

    case FOCUS:
      if (value == null) {
        unsetFocus();
      } else {
        setFocus((java.lang.Boolean)value);
      }
      break;

    case DERIVATION_CONFIG:
      if (value == null) {
        unsetDerivationConfig();
      } else {
        setDerivationConfig((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VERSION_ID:
      return getVersionId();

    case DATASET_NAME:
      return getDatasetName();

    case VERSION_NO:
      return getVersionNo();

    case PROVENANCE_TYPE:
      return getProvenanceType();

    case PROVENANCE_LABEL:
      return getProvenanceLabel();

    case STORAGE_PATH:
      return getStoragePath();

    case OPERATOR:
      return getOperator();

    case CLIENT_IP:
      return getClientIp();

    case CREATE_TIME:
      return getCreateTime();

    case REMARK:
      return getRemark();

    case DELETED:
      return isDeleted();

    case JOB_STATE:
      return getJobState();

    case FOCUS:
      return isFocus();

    case DERIVATION_CONFIG:
      return getDerivationConfig();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VERSION_ID:
      return isSetVersionId();
    case DATASET_NAME:
      return isSetDatasetName();
    case VERSION_NO:
      return isSetVersionNo();
    case PROVENANCE_TYPE:
      return isSetProvenanceType();
    case PROVENANCE_LABEL:
      return isSetProvenanceLabel();
    case STORAGE_PATH:
      return isSetStoragePath();
    case OPERATOR:
      return isSetOperator();
    case CLIENT_IP:
      return isSetClientIp();
    case CREATE_TIME:
      return isSetCreateTime();
    case REMARK:
      return isSetRemark();
    case DELETED:
      return isSetDeleted();
    case JOB_STATE:
      return isSetJobState();
    case FOCUS:
      return isSetFocus();
    case DERIVATION_CONFIG:
      return isSetDerivationConfig();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LineageNode)
      return this.equals((LineageNode)that);
    return false;
  }

  public boolean equals(LineageNode that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_versionId = true;
    boolean that_present_versionId = true;
    if (this_present_versionId || that_present_versionId) {
      if (!(this_present_versionId && that_present_versionId))
        return false;
      if (this.versionId != that.versionId)
        return false;
    }

    boolean this_present_datasetName = true && this.isSetDatasetName();
    boolean that_present_datasetName = true && that.isSetDatasetName();
    if (this_present_datasetName || that_present_datasetName) {
      if (!(this_present_datasetName && that_present_datasetName))
        return false;
      if (!this.datasetName.equals(that.datasetName))
        return false;
    }

    boolean this_present_versionNo = true && this.isSetVersionNo();
    boolean that_present_versionNo = true && that.isSetVersionNo();
    if (this_present_versionNo || that_present_versionNo) {
      if (!(this_present_versionNo && that_present_versionNo))
        return false;
      if (!this.versionNo.equals(that.versionNo))
        return false;
    }

    boolean this_present_provenanceType = true && this.isSetProvenanceType();
    boolean that_present_provenanceType = true && that.isSetProvenanceType();
    if (this_present_provenanceType || that_present_provenanceType) {
      if (!(this_present_provenanceType && that_present_provenanceType))
        return false;
      if (!this.provenanceType.equals(that.provenanceType))
        return false;
    }

    boolean this_present_provenanceLabel = true && this.isSetProvenanceLabel();
    boolean that_present_provenanceLabel = true && that.isSetProvenanceLabel();
    if (this_present_provenanceLabel || that_present_provenanceLabel) {
      if (!(this_present_provenanceLabel && that_present_provenanceLabel))
        return false;
      if (!this.provenanceLabel.equals(that.provenanceLabel))
        return false;
    }

    boolean this_present_storagePath = true && this.isSetStoragePath();
    boolean that_present_storagePath = true && that.isSetStoragePath();
    if (this_present_storagePath || that_present_storagePath) {
      if (!(this_present_storagePath && that_present_storagePath))
        return false;
      if (!this.storagePath.equals(that.storagePath))
        return false;
    }

    boolean this_present_operator = true && this.isSetOperator();
    boolean that_present_operator = true && that.isSetOperator();
    if (this_present_operator || that_present_operator) {
      if (!(this_present_operator && that_present_operator))
        return false;
      if (!this.operator.equals(that.operator))
        return false;
    }

    boolean this_present_clientIp = true && this.isSetClientIp();
    boolean that_present_clientIp = true && that.isSetClientIp();
    if (this_present_clientIp || that_present_clientIp) {
      if (!(this_present_clientIp && that_present_clientIp))
        return false;
      if (!this.clientIp.equals(that.clientIp))
        return false;
    }

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_remark = true && this.isSetRemark();
    boolean that_present_remark = true && that.isSetRemark();
    if (this_present_remark || that_present_remark) {
      if (!(this_present_remark && that_present_remark))
        return false;
      if (!this.remark.equals(that.remark))
        return false;
    }

    boolean this_present_deleted = true;
    boolean that_present_deleted = true;
    if (this_present_deleted || that_present_deleted) {
      if (!(this_present_deleted && that_present_deleted))
        return false;
      if (this.deleted != that.deleted)
        return false;
    }

    boolean this_present_jobState = true && this.isSetJobState();
    boolean that_present_jobState = true && that.isSetJobState();
    if (this_present_jobState || that_present_jobState) {
      if (!(this_present_jobState && that_present_jobState))
        return false;
      if (this.jobState != that.jobState)
        return false;
    }

    boolean this_present_focus = true;
    boolean that_present_focus = true;
    if (this_present_focus || that_present_focus) {
      if (!(this_present_focus && that_present_focus))
        return false;
      if (this.focus != that.focus)
        return false;
    }

    boolean this_present_derivationConfig = true && this.isSetDerivationConfig();
    boolean that_present_derivationConfig = true && that.isSetDerivationConfig();
    if (this_present_derivationConfig || that_present_derivationConfig) {
      if (!(this_present_derivationConfig && that_present_derivationConfig))
        return false;
      if (!this.derivationConfig.equals(that.derivationConfig))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(versionId);

    hashCode = hashCode * 8191 + ((isSetDatasetName()) ? 131071 : 524287);
    if (isSetDatasetName())
      hashCode = hashCode * 8191 + datasetName.hashCode();

    hashCode = hashCode * 8191 + ((isSetVersionNo()) ? 131071 : 524287);
    if (isSetVersionNo())
      hashCode = hashCode * 8191 + versionNo.hashCode();

    hashCode = hashCode * 8191 + ((isSetProvenanceType()) ? 131071 : 524287);
    if (isSetProvenanceType())
      hashCode = hashCode * 8191 + provenanceType.hashCode();

    hashCode = hashCode * 8191 + ((isSetProvenanceLabel()) ? 131071 : 524287);
    if (isSetProvenanceLabel())
      hashCode = hashCode * 8191 + provenanceLabel.hashCode();

    hashCode = hashCode * 8191 + ((isSetStoragePath()) ? 131071 : 524287);
    if (isSetStoragePath())
      hashCode = hashCode * 8191 + storagePath.hashCode();

    hashCode = hashCode * 8191 + ((isSetOperator()) ? 131071 : 524287);
    if (isSetOperator())
      hashCode = hashCode * 8191 + operator.hashCode();

    hashCode = hashCode * 8191 + ((isSetClientIp()) ? 131071 : 524287);
    if (isSetClientIp())
      hashCode = hashCode * 8191 + clientIp.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + ((isSetRemark()) ? 131071 : 524287);
    if (isSetRemark())
      hashCode = hashCode * 8191 + remark.hashCode();

    hashCode = hashCode * 8191 + ((deleted) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetJobState()) ? 131071 : 524287);
    if (isSetJobState())
      hashCode = hashCode * 8191 + jobState;

    hashCode = hashCode * 8191 + ((focus) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetDerivationConfig()) ? 131071 : 524287);
    if (isSetDerivationConfig())
      hashCode = hashCode * 8191 + derivationConfig.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LineageNode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetVersionId(), other.isSetVersionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionId, other.versionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDatasetName(), other.isSetDatasetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatasetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datasetName, other.datasetName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVersionNo(), other.isSetVersionNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionNo, other.versionNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProvenanceType(), other.isSetProvenanceType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvenanceType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provenanceType, other.provenanceType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProvenanceLabel(), other.isSetProvenanceLabel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvenanceLabel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provenanceLabel, other.provenanceLabel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStoragePath(), other.isSetStoragePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStoragePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.storagePath, other.storagePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOperator(), other.isSetOperator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operator, other.operator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetClientIp(), other.isSetClientIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientIp, other.clientIp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRemark(), other.isSetRemark());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemark()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remark, other.remark);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDeleted(), other.isSetDeleted());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeleted()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deleted, other.deleted);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetJobState(), other.isSetJobState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJobState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jobState, other.jobState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFocus(), other.isSetFocus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFocus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.focus, other.focus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDerivationConfig(), other.isSetDerivationConfig());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDerivationConfig()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.derivationConfig, other.derivationConfig);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LineageNode(");
    boolean first = true;

    sb.append("versionId:");
    sb.append(this.versionId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("datasetName:");
    if (this.datasetName == null) {
      sb.append("null");
    } else {
      sb.append(this.datasetName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("versionNo:");
    if (this.versionNo == null) {
      sb.append("null");
    } else {
      sb.append(this.versionNo);
    }
    first = false;
    if (isSetProvenanceType()) {
      if (!first) sb.append(", ");
      sb.append("provenanceType:");
      if (this.provenanceType == null) {
        sb.append("null");
      } else {
        sb.append(this.provenanceType);
      }
      first = false;
    }
    if (isSetProvenanceLabel()) {
      if (!first) sb.append(", ");
      sb.append("provenanceLabel:");
      if (this.provenanceLabel == null) {
        sb.append("null");
      } else {
        sb.append(this.provenanceLabel);
      }
      first = false;
    }
    if (isSetStoragePath()) {
      if (!first) sb.append(", ");
      sb.append("storagePath:");
      if (this.storagePath == null) {
        sb.append("null");
      } else {
        sb.append(this.storagePath);
      }
      first = false;
    }
    if (isSetOperator()) {
      if (!first) sb.append(", ");
      sb.append("operator:");
      if (this.operator == null) {
        sb.append("null");
      } else {
        sb.append(this.operator);
      }
      first = false;
    }
    if (isSetClientIp()) {
      if (!first) sb.append(", ");
      sb.append("clientIp:");
      if (this.clientIp == null) {
        sb.append("null");
      } else {
        sb.append(this.clientIp);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    if (isSetRemark()) {
      if (!first) sb.append(", ");
      sb.append("remark:");
      if (this.remark == null) {
        sb.append("null");
      } else {
        sb.append(this.remark);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("deleted:");
    sb.append(this.deleted);
    first = false;
    if (isSetJobState()) {
      if (!first) sb.append(", ");
      sb.append("jobState:");
      sb.append(this.jobState);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("focus:");
    sb.append(this.focus);
    first = false;
    if (isSetDerivationConfig()) {
      if (!first) sb.append(", ");
      sb.append("derivationConfig:");
      if (this.derivationConfig == null) {
        sb.append("null");
      } else {
        sb.append(this.derivationConfig);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LineageNodeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LineageNodeStandardScheme getScheme() {
      return new LineageNodeStandardScheme();
    }
  }

  private static class LineageNodeStandardScheme extends org.apache.thrift.scheme.StandardScheme<LineageNode> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LineageNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VERSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.versionId = iprot.readI64();
              struct.setVersionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATASET_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.datasetName = iprot.readString();
              struct.setDatasetNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERSION_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.versionNo = iprot.readString();
              struct.setVersionNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PROVENANCE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.provenanceType = iprot.readString();
              struct.setProvenanceTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PROVENANCE_LABEL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.provenanceLabel = iprot.readString();
              struct.setProvenanceLabelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // STORAGE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.storagePath = iprot.readString();
              struct.setStoragePathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // OPERATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.operator = iprot.readString();
              struct.setOperatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // CLIENT_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientIp = iprot.readString();
              struct.setClientIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // REMARK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.remark = iprot.readString();
              struct.setRemarkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // DELETED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.deleted = iprot.readBool();
              struct.setDeletedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // JOB_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.jobState = iprot.readI32();
              struct.setJobStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // FOCUS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.focus = iprot.readBool();
              struct.setFocusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // DERIVATION_CONFIG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.derivationConfig = iprot.readString();
              struct.setDerivationConfigIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LineageNode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VERSION_ID_FIELD_DESC);
      oprot.writeI64(struct.versionId);
      oprot.writeFieldEnd();
      if (struct.datasetName != null) {
        oprot.writeFieldBegin(DATASET_NAME_FIELD_DESC);
        oprot.writeString(struct.datasetName);
        oprot.writeFieldEnd();
      }
      if (struct.versionNo != null) {
        oprot.writeFieldBegin(VERSION_NO_FIELD_DESC);
        oprot.writeString(struct.versionNo);
        oprot.writeFieldEnd();
      }
      if (struct.provenanceType != null) {
        if (struct.isSetProvenanceType()) {
          oprot.writeFieldBegin(PROVENANCE_TYPE_FIELD_DESC);
          oprot.writeString(struct.provenanceType);
          oprot.writeFieldEnd();
        }
      }
      if (struct.provenanceLabel != null) {
        if (struct.isSetProvenanceLabel()) {
          oprot.writeFieldBegin(PROVENANCE_LABEL_FIELD_DESC);
          oprot.writeString(struct.provenanceLabel);
          oprot.writeFieldEnd();
        }
      }
      if (struct.storagePath != null) {
        if (struct.isSetStoragePath()) {
          oprot.writeFieldBegin(STORAGE_PATH_FIELD_DESC);
          oprot.writeString(struct.storagePath);
          oprot.writeFieldEnd();
        }
      }
      if (struct.operator != null) {
        if (struct.isSetOperator()) {
          oprot.writeFieldBegin(OPERATOR_FIELD_DESC);
          oprot.writeString(struct.operator);
          oprot.writeFieldEnd();
        }
      }
      if (struct.clientIp != null) {
        if (struct.isSetClientIp()) {
          oprot.writeFieldBegin(CLIENT_IP_FIELD_DESC);
          oprot.writeString(struct.clientIp);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      if (struct.remark != null) {
        if (struct.isSetRemark()) {
          oprot.writeFieldBegin(REMARK_FIELD_DESC);
          oprot.writeString(struct.remark);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(DELETED_FIELD_DESC);
      oprot.writeBool(struct.deleted);
      oprot.writeFieldEnd();
      if (struct.isSetJobState()) {
        oprot.writeFieldBegin(JOB_STATE_FIELD_DESC);
        oprot.writeI32(struct.jobState);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FOCUS_FIELD_DESC);
      oprot.writeBool(struct.focus);
      oprot.writeFieldEnd();
      if (struct.derivationConfig != null) {
        if (struct.isSetDerivationConfig()) {
          oprot.writeFieldBegin(DERIVATION_CONFIG_FIELD_DESC);
          oprot.writeString(struct.derivationConfig);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LineageNodeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LineageNodeTupleScheme getScheme() {
      return new LineageNodeTupleScheme();
    }
  }

  private static class LineageNodeTupleScheme extends org.apache.thrift.scheme.TupleScheme<LineageNode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LineageNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVersionId()) {
        optionals.set(0);
      }
      if (struct.isSetDatasetName()) {
        optionals.set(1);
      }
      if (struct.isSetVersionNo()) {
        optionals.set(2);
      }
      if (struct.isSetProvenanceType()) {
        optionals.set(3);
      }
      if (struct.isSetProvenanceLabel()) {
        optionals.set(4);
      }
      if (struct.isSetStoragePath()) {
        optionals.set(5);
      }
      if (struct.isSetOperator()) {
        optionals.set(6);
      }
      if (struct.isSetClientIp()) {
        optionals.set(7);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(8);
      }
      if (struct.isSetRemark()) {
        optionals.set(9);
      }
      if (struct.isSetDeleted()) {
        optionals.set(10);
      }
      if (struct.isSetJobState()) {
        optionals.set(11);
      }
      if (struct.isSetFocus()) {
        optionals.set(12);
      }
      if (struct.isSetDerivationConfig()) {
        optionals.set(13);
      }
      oprot.writeBitSet(optionals, 14);
      if (struct.isSetVersionId()) {
        oprot.writeI64(struct.versionId);
      }
      if (struct.isSetDatasetName()) {
        oprot.writeString(struct.datasetName);
      }
      if (struct.isSetVersionNo()) {
        oprot.writeString(struct.versionNo);
      }
      if (struct.isSetProvenanceType()) {
        oprot.writeString(struct.provenanceType);
      }
      if (struct.isSetProvenanceLabel()) {
        oprot.writeString(struct.provenanceLabel);
      }
      if (struct.isSetStoragePath()) {
        oprot.writeString(struct.storagePath);
      }
      if (struct.isSetOperator()) {
        oprot.writeString(struct.operator);
      }
      if (struct.isSetClientIp()) {
        oprot.writeString(struct.clientIp);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetRemark()) {
        oprot.writeString(struct.remark);
      }
      if (struct.isSetDeleted()) {
        oprot.writeBool(struct.deleted);
      }
      if (struct.isSetJobState()) {
        oprot.writeI32(struct.jobState);
      }
      if (struct.isSetFocus()) {
        oprot.writeBool(struct.focus);
      }
      if (struct.isSetDerivationConfig()) {
        oprot.writeString(struct.derivationConfig);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LineageNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(14);
      if (incoming.get(0)) {
        struct.versionId = iprot.readI64();
        struct.setVersionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.datasetName = iprot.readString();
        struct.setDatasetNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.versionNo = iprot.readString();
        struct.setVersionNoIsSet(true);
      }
      if (incoming.get(3)) {
        struct.provenanceType = iprot.readString();
        struct.setProvenanceTypeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.provenanceLabel = iprot.readString();
        struct.setProvenanceLabelIsSet(true);
      }
      if (incoming.get(5)) {
        struct.storagePath = iprot.readString();
        struct.setStoragePathIsSet(true);
      }
      if (incoming.get(6)) {
        struct.operator = iprot.readString();
        struct.setOperatorIsSet(true);
      }
      if (incoming.get(7)) {
        struct.clientIp = iprot.readString();
        struct.setClientIpIsSet(true);
      }
      if (incoming.get(8)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(9)) {
        struct.remark = iprot.readString();
        struct.setRemarkIsSet(true);
      }
      if (incoming.get(10)) {
        struct.deleted = iprot.readBool();
        struct.setDeletedIsSet(true);
      }
      if (incoming.get(11)) {
        struct.jobState = iprot.readI32();
        struct.setJobStateIsSet(true);
      }
      if (incoming.get(12)) {
        struct.focus = iprot.readBool();
        struct.setFocusIsSet(true);
      }
      if (incoming.get(13)) {
        struct.derivationConfig = iprot.readString();
        struct.setDerivationConfigIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

