/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-09-10")
public class UpstreamRef implements org.apache.thrift.TBase<UpstreamRef, UpstreamRef._Fields>, java.io.Serializable, Cloneable, Comparable<UpstreamRef> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UpstreamRef");

  private static final org.apache.thrift.protocol.TField VERSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("versionId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField DATASET_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("datasetName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VERSION_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("versionNo", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PRIMARY_FIELD_DESC = new org.apache.thrift.protocol.TField("primary", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UpstreamRefStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UpstreamRefTupleSchemeFactory();

  public long versionId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String datasetName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String versionNo; // optional
  public boolean primary; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VERSION_ID((short)1, "versionId"),
    DATASET_NAME((short)2, "datasetName"),
    VERSION_NO((short)3, "versionNo"),
    PRIMARY((short)4, "primary");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VERSION_ID
          return VERSION_ID;
        case 2: // DATASET_NAME
          return DATASET_NAME;
        case 3: // VERSION_NO
          return VERSION_NO;
        case 4: // PRIMARY
          return PRIMARY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERSIONID_ISSET_ID = 0;
  private static final int __PRIMARY_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.DATASET_NAME,_Fields.VERSION_NO};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VERSION_ID, new org.apache.thrift.meta_data.FieldMetaData("versionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DATASET_NAME, new org.apache.thrift.meta_data.FieldMetaData("datasetName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_NO, new org.apache.thrift.meta_data.FieldMetaData("versionNo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIMARY, new org.apache.thrift.meta_data.FieldMetaData("primary", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UpstreamRef.class, metaDataMap);
  }

  public UpstreamRef() {
  }

  public UpstreamRef(
    long versionId,
    boolean primary)
  {
    this();
    this.versionId = versionId;
    setVersionIdIsSet(true);
    this.primary = primary;
    setPrimaryIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UpstreamRef(UpstreamRef other) {
    __isset_bitfield = other.__isset_bitfield;
    this.versionId = other.versionId;
    if (other.isSetDatasetName()) {
      this.datasetName = other.datasetName;
    }
    if (other.isSetVersionNo()) {
      this.versionNo = other.versionNo;
    }
    this.primary = other.primary;
  }

  @Override
  public UpstreamRef deepCopy() {
    return new UpstreamRef(this);
  }

  @Override
  public void clear() {
    setVersionIdIsSet(false);
    this.versionId = 0;
    this.datasetName = null;
    this.versionNo = null;
    setPrimaryIsSet(false);
    this.primary = false;
  }

  public long getVersionId() {
    return this.versionId;
  }

  public UpstreamRef setVersionId(long versionId) {
    this.versionId = versionId;
    setVersionIdIsSet(true);
    return this;
  }

  public void unsetVersionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERSIONID_ISSET_ID);
  }

  /** Returns true if field versionId is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERSIONID_ISSET_ID);
  }

  public void setVersionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERSIONID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDatasetName() {
    return this.datasetName;
  }

  public UpstreamRef setDatasetName(@org.apache.thrift.annotation.Nullable java.lang.String datasetName) {
    this.datasetName = datasetName;
    return this;
  }

  public void unsetDatasetName() {
    this.datasetName = null;
  }

  /** Returns true if field datasetName is set (has been assigned a value) and false otherwise */
  public boolean isSetDatasetName() {
    return this.datasetName != null;
  }

  public void setDatasetNameIsSet(boolean value) {
    if (!value) {
      this.datasetName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getVersionNo() {
    return this.versionNo;
  }

  public UpstreamRef setVersionNo(@org.apache.thrift.annotation.Nullable java.lang.String versionNo) {
    this.versionNo = versionNo;
    return this;
  }

  public void unsetVersionNo() {
    this.versionNo = null;
  }

  /** Returns true if field versionNo is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionNo() {
    return this.versionNo != null;
  }

  public void setVersionNoIsSet(boolean value) {
    if (!value) {
      this.versionNo = null;
    }
  }

  public boolean isPrimary() {
    return this.primary;
  }

  public UpstreamRef setPrimary(boolean primary) {
    this.primary = primary;
    setPrimaryIsSet(true);
    return this;
  }

  public void unsetPrimary() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRIMARY_ISSET_ID);
  }

  /** Returns true if field primary is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimary() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRIMARY_ISSET_ID);
  }

  public void setPrimaryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRIMARY_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case VERSION_ID:
      if (value == null) {
        unsetVersionId();
      } else {
        setVersionId((java.lang.Long)value);
      }
      break;

    case DATASET_NAME:
      if (value == null) {
        unsetDatasetName();
      } else {
        setDatasetName((java.lang.String)value);
      }
      break;

    case VERSION_NO:
      if (value == null) {
        unsetVersionNo();
      } else {
        setVersionNo((java.lang.String)value);
      }
      break;

    case PRIMARY:
      if (value == null) {
        unsetPrimary();
      } else {
        setPrimary((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VERSION_ID:
      return getVersionId();

    case DATASET_NAME:
      return getDatasetName();

    case VERSION_NO:
      return getVersionNo();

    case PRIMARY:
      return isPrimary();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VERSION_ID:
      return isSetVersionId();
    case DATASET_NAME:
      return isSetDatasetName();
    case VERSION_NO:
      return isSetVersionNo();
    case PRIMARY:
      return isSetPrimary();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof UpstreamRef)
      return this.equals((UpstreamRef)that);
    return false;
  }

  public boolean equals(UpstreamRef that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_versionId = true;
    boolean that_present_versionId = true;
    if (this_present_versionId || that_present_versionId) {
      if (!(this_present_versionId && that_present_versionId))
        return false;
      if (this.versionId != that.versionId)
        return false;
    }

    boolean this_present_datasetName = true && this.isSetDatasetName();
    boolean that_present_datasetName = true && that.isSetDatasetName();
    if (this_present_datasetName || that_present_datasetName) {
      if (!(this_present_datasetName && that_present_datasetName))
        return false;
      if (!this.datasetName.equals(that.datasetName))
        return false;
    }

    boolean this_present_versionNo = true && this.isSetVersionNo();
    boolean that_present_versionNo = true && that.isSetVersionNo();
    if (this_present_versionNo || that_present_versionNo) {
      if (!(this_present_versionNo && that_present_versionNo))
        return false;
      if (!this.versionNo.equals(that.versionNo))
        return false;
    }

    boolean this_present_primary = true;
    boolean that_present_primary = true;
    if (this_present_primary || that_present_primary) {
      if (!(this_present_primary && that_present_primary))
        return false;
      if (this.primary != that.primary)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(versionId);

    hashCode = hashCode * 8191 + ((isSetDatasetName()) ? 131071 : 524287);
    if (isSetDatasetName())
      hashCode = hashCode * 8191 + datasetName.hashCode();

    hashCode = hashCode * 8191 + ((isSetVersionNo()) ? 131071 : 524287);
    if (isSetVersionNo())
      hashCode = hashCode * 8191 + versionNo.hashCode();

    hashCode = hashCode * 8191 + ((primary) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(UpstreamRef other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetVersionId(), other.isSetVersionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionId, other.versionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDatasetName(), other.isSetDatasetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatasetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datasetName, other.datasetName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVersionNo(), other.isSetVersionNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionNo, other.versionNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPrimary(), other.isSetPrimary());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimary()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primary, other.primary);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("UpstreamRef(");
    boolean first = true;

    sb.append("versionId:");
    sb.append(this.versionId);
    first = false;
    if (isSetDatasetName()) {
      if (!first) sb.append(", ");
      sb.append("datasetName:");
      if (this.datasetName == null) {
        sb.append("null");
      } else {
        sb.append(this.datasetName);
      }
      first = false;
    }
    if (isSetVersionNo()) {
      if (!first) sb.append(", ");
      sb.append("versionNo:");
      if (this.versionNo == null) {
        sb.append("null");
      } else {
        sb.append(this.versionNo);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("primary:");
    sb.append(this.primary);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UpstreamRefStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UpstreamRefStandardScheme getScheme() {
      return new UpstreamRefStandardScheme();
    }
  }

  private static class UpstreamRefStandardScheme extends org.apache.thrift.scheme.StandardScheme<UpstreamRef> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, UpstreamRef struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VERSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.versionId = iprot.readI64();
              struct.setVersionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATASET_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.datasetName = iprot.readString();
              struct.setDatasetNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERSION_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.versionNo = iprot.readString();
              struct.setVersionNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PRIMARY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.primary = iprot.readBool();
              struct.setPrimaryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, UpstreamRef struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VERSION_ID_FIELD_DESC);
      oprot.writeI64(struct.versionId);
      oprot.writeFieldEnd();
      if (struct.datasetName != null) {
        if (struct.isSetDatasetName()) {
          oprot.writeFieldBegin(DATASET_NAME_FIELD_DESC);
          oprot.writeString(struct.datasetName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.versionNo != null) {
        if (struct.isSetVersionNo()) {
          oprot.writeFieldBegin(VERSION_NO_FIELD_DESC);
          oprot.writeString(struct.versionNo);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(PRIMARY_FIELD_DESC);
      oprot.writeBool(struct.primary);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UpstreamRefTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UpstreamRefTupleScheme getScheme() {
      return new UpstreamRefTupleScheme();
    }
  }

  private static class UpstreamRefTupleScheme extends org.apache.thrift.scheme.TupleScheme<UpstreamRef> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UpstreamRef struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVersionId()) {
        optionals.set(0);
      }
      if (struct.isSetDatasetName()) {
        optionals.set(1);
      }
      if (struct.isSetVersionNo()) {
        optionals.set(2);
      }
      if (struct.isSetPrimary()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetVersionId()) {
        oprot.writeI64(struct.versionId);
      }
      if (struct.isSetDatasetName()) {
        oprot.writeString(struct.datasetName);
      }
      if (struct.isSetVersionNo()) {
        oprot.writeString(struct.versionNo);
      }
      if (struct.isSetPrimary()) {
        oprot.writeBool(struct.primary);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UpstreamRef struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.versionId = iprot.readI64();
        struct.setVersionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.datasetName = iprot.readString();
        struct.setDatasetNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.versionNo = iprot.readString();
        struct.setVersionNoIsSet(true);
      }
      if (incoming.get(3)) {
        struct.primary = iprot.readBool();
        struct.setPrimaryIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

