// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"tsinghua/api"
)

var _ = api.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  Result registerDataSource(string jsonBody)")
	fmt.Fprintln(os.Stderr, "  Result removeDataSource(StorageEngineInfo storageEngineInfo)")
	fmt.Fprintln(os.Stderr, "  Result listDataSources()")
	fmt.Fprintln(os.Stderr, "  Result getDataSourceTree()")
	fmt.Fprintln(os.Stderr, "  Result queryData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryFileData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result importData(DataImportRequest config, string file)")
	fmt.Fprintln(os.Stderr, "  string exportData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result deleteData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getTimeRange(TimeRangeRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  string exportRelationalDataToExcel(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result testSQL(string sql)")
	fmt.Fprintln(os.Stderr, "  Result saveDataset(DatasetRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryMeta(string path)")
	fmt.Fprintln(os.Stderr, "  Result deleteDataset(string path)")
	fmt.Fprintln(os.Stderr, "  Result getVersionHistory(string datasetName)")
	fmt.Fprintln(os.Stderr, "  Result registerTransform(string file, string name, string className)")
	fmt.Fprintln(os.Stderr, "  Result deleteFunction(string name)")
	fmt.Fprintln(os.Stderr, "  Result listFunctions(string type)")
	fmt.Fprintln(os.Stderr, "  Result registerUDF(string file, string name, string className, string udfType)")
	fmt.Fprintln(os.Stderr, "  string downloadFunction(string type, string fileName)")
	fmt.Fprintln(os.Stderr, "  Result saveTransformCompare(TransformJobRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryTransformCompares(TransformJobQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countTransformCompares(TransformJobQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getTransformCompare(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result deleteTransformCompare(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result queryTransformJobs(TransformJobQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countTransformJobs(TransformJobQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getTransformJob(string jobId)")
	fmt.Fprintln(os.Stderr, "  Result commitTransformJob(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result getTransformJobStatus(string jobId)")
	fmt.Fprintln(os.Stderr, "  Result cancelTransformJob(string jobId)")
	fmt.Fprintln(os.Stderr, "  Result getTransformJobBloodline(string datasetPath, bool sideLineage)")
	fmt.Fprintln(os.Stderr, "  string getUserManualFile()")
	fmt.Fprintln(os.Stderr, "  Result generateJavaCode()")
	fmt.Fprintln(os.Stderr, "  Result generateGoCode()")
	fmt.Fprintln(os.Stderr, "  Result generatePythonCode()")
	fmt.Fprintln(os.Stderr, "  Result generateRestfulApiCode()")
	fmt.Fprintln(os.Stderr, "  Result generateAllCode()")
	fmt.Fprintln(os.Stderr, "  Result getGenerationStatus()")
	fmt.Fprintln(os.Stderr, "  Result validateThriftFile()")
	fmt.Fprintln(os.Stderr, "  Result login(LoginRequest request)")
	fmt.Fprintln(os.Stderr, "  Result refreshToken(RefreshTokenRequest request)")
	fmt.Fprintln(os.Stderr, "  Result verifyToken()")
	fmt.Fprintln(os.Stderr, "  Result logout()")
	fmt.Fprintln(os.Stderr, "  Result getCurrentAuthUser()")
	fmt.Fprintln(os.Stderr, "  Result saveUser(UserEntity user)")
	fmt.Fprintln(os.Stderr, "  Result queryUsers(UserQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countUsers(UserQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result allUsers()")
	fmt.Fprintln(os.Stderr, "  Result queryUser(string username)")
	fmt.Fprintln(os.Stderr, "  Result deleteUser(string username)")
	fmt.Fprintln(os.Stderr, "  Result updateUser(UserEntity user)")
	fmt.Fprintln(os.Stderr, "  Result getRoles()")
	fmt.Fprintln(os.Stderr, "  Result changePassword(ChangePasswordRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getCurrentUser()")
	fmt.Fprintln(os.Stderr, "  Result listOwnerTables()")
	fmt.Fprintln(os.Stderr, "  Result queryDataPermissions(DataPermissionQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countDataPermissions(DataPermissionQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result updateDataPermission(DataPermissionUpdateRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := api.NewApiServiceClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "registerDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RegisterDataSource requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.RegisterDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "removeDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveDataSource requires 1 args")
			flag.Usage()
		}
		arg390 := flag.Arg(1)
		mbTrans391 := thrift.NewTMemoryBufferLen(len(arg390))
		defer mbTrans391.Close()
		_, err392 := mbTrans391.WriteString(arg390)
		if err392 != nil {
			Usage()
			return
		}
		factory393 := thrift.NewTJSONProtocolFactory()
		jsProt394 := factory393.GetProtocol(mbTrans391)
		argvalue0 := api.NewStorageEngineInfo()
		err395 := argvalue0.Read(context.Background(), jsProt394)
		if err395 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "listDataSources":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ListDataSources requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListDataSources(context.Background()))
		fmt.Print("\n")
		break
	case "getDataSourceTree":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetDataSourceTree requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetDataSourceTree(context.Background()))
		fmt.Print("\n")
		break
	case "queryData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryData requires 1 args")
			flag.Usage()
		}
		arg396 := flag.Arg(1)
		mbTrans397 := thrift.NewTMemoryBufferLen(len(arg396))
		defer mbTrans397.Close()
		_, err398 := mbTrans397.WriteString(arg396)
		if err398 != nil {
			Usage()
			return
		}
		factory399 := thrift.NewTJSONProtocolFactory()
		jsProt400 := factory399.GetProtocol(mbTrans397)
		argvalue0 := api.NewDataQueryRequest()
		err401 := argvalue0.Read(context.Background(), jsProt400)
		if err401 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryFileData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryFileData requires 1 args")
			flag.Usage()
		}
		arg402 := flag.Arg(1)
		mbTrans403 := thrift.NewTMemoryBufferLen(len(arg402))
		defer mbTrans403.Close()
		_, err404 := mbTrans403.WriteString(arg402)
		if err404 != nil {
			Usage()
			return
		}
		factory405 := thrift.NewTJSONProtocolFactory()
		jsProt406 := factory405.GetProtocol(mbTrans403)
		argvalue0 := api.NewDataQueryRequest()
		err407 := argvalue0.Read(context.Background(), jsProt406)
		if err407 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryFileData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "importData":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ImportData requires 2 args")
			flag.Usage()
		}
		arg408 := flag.Arg(1)
		mbTrans409 := thrift.NewTMemoryBufferLen(len(arg408))
		defer mbTrans409.Close()
		_, err410 := mbTrans409.WriteString(arg408)
		if err410 != nil {
			Usage()
			return
		}
		factory411 := thrift.NewTJSONProtocolFactory()
		jsProt412 := factory411.GetProtocol(mbTrans409)
		argvalue0 := api.NewDataImportRequest()
		err413 := argvalue0.Read(context.Background(), jsProt412)
		if err413 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1 := []byte(flag.Arg(2))
		value1 := argvalue1
		fmt.Print(client.ImportData(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "exportData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExportData requires 1 args")
			flag.Usage()
		}
		arg415 := flag.Arg(1)
		mbTrans416 := thrift.NewTMemoryBufferLen(len(arg415))
		defer mbTrans416.Close()
		_, err417 := mbTrans416.WriteString(arg415)
		if err417 != nil {
			Usage()
			return
		}
		factory418 := thrift.NewTJSONProtocolFactory()
		jsProt419 := factory418.GetProtocol(mbTrans416)
		argvalue0 := api.NewDataQueryRequest()
		err420 := argvalue0.Read(context.Background(), jsProt419)
		if err420 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExportData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteData requires 1 args")
			flag.Usage()
		}
		arg421 := flag.Arg(1)
		mbTrans422 := thrift.NewTMemoryBufferLen(len(arg421))
		defer mbTrans422.Close()
		_, err423 := mbTrans422.WriteString(arg421)
		if err423 != nil {
			Usage()
			return
		}
		factory424 := thrift.NewTJSONProtocolFactory()
		jsProt425 := factory424.GetProtocol(mbTrans422)
		argvalue0 := api.NewDataQueryRequest()
		err426 := argvalue0.Read(context.Background(), jsProt425)
		if err426 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTimeRange":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTimeRange requires 1 args")
			flag.Usage()
		}
		arg427 := flag.Arg(1)
		mbTrans428 := thrift.NewTMemoryBufferLen(len(arg427))
		defer mbTrans428.Close()
		_, err429 := mbTrans428.WriteString(arg427)
		if err429 != nil {
			Usage()
			return
		}
		factory430 := thrift.NewTJSONProtocolFactory()
		jsProt431 := factory430.GetProtocol(mbTrans428)
		argvalue0 := api.NewTimeRangeRequest()
		err432 := argvalue0.Read(context.Background(), jsProt431)
		if err432 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTimeRange(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryRelationalData requires 1 args")
			flag.Usage()
		}
		arg433 := flag.Arg(1)
		mbTrans434 := thrift.NewTMemoryBufferLen(len(arg433))
		defer mbTrans434.Close()
		_, err435 := mbTrans434.WriteString(arg433)
		if err435 != nil {
			Usage()
			return
		}
		factory436 := thrift.NewTJSONProtocolFactory()
		jsProt437 := factory436.GetProtocol(mbTrans434)
		argvalue0 := api.NewRelationalQueryRequest()
		err438 := argvalue0.Read(context.Background(), jsProt437)
		if err438 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountRelationalData requires 1 args")
			flag.Usage()
		}
		arg439 := flag.Arg(1)
		mbTrans440 := thrift.NewTMemoryBufferLen(len(arg439))
		defer mbTrans440.Close()
		_, err441 := mbTrans440.WriteString(arg439)
		if err441 != nil {
			Usage()
			return
		}
		factory442 := thrift.NewTJSONProtocolFactory()
		jsProt443 := factory442.GetProtocol(mbTrans440)
		argvalue0 := api.NewRelationalQueryRequest()
		err444 := argvalue0.Read(context.Background(), jsProt443)
		if err444 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "exportRelationalDataToExcel":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExportRelationalDataToExcel requires 1 args")
			flag.Usage()
		}
		arg445 := flag.Arg(1)
		mbTrans446 := thrift.NewTMemoryBufferLen(len(arg445))
		defer mbTrans446.Close()
		_, err447 := mbTrans446.WriteString(arg445)
		if err447 != nil {
			Usage()
			return
		}
		factory448 := thrift.NewTJSONProtocolFactory()
		jsProt449 := factory448.GetProtocol(mbTrans446)
		argvalue0 := api.NewRelationalQueryRequest()
		err450 := argvalue0.Read(context.Background(), jsProt449)
		if err450 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExportRelationalDataToExcel(context.Background(), value0))
		fmt.Print("\n")
		break
	case "testSQL":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "TestSQL requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.TestSQL(context.Background(), value0))
		fmt.Print("\n")
		break
	case "saveDataset":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveDataset requires 1 args")
			flag.Usage()
		}
		arg452 := flag.Arg(1)
		mbTrans453 := thrift.NewTMemoryBufferLen(len(arg452))
		defer mbTrans453.Close()
		_, err454 := mbTrans453.WriteString(arg452)
		if err454 != nil {
			Usage()
			return
		}
		factory455 := thrift.NewTJSONProtocolFactory()
		jsProt456 := factory455.GetProtocol(mbTrans453)
		argvalue0 := api.NewDatasetRequest()
		err457 := argvalue0.Read(context.Background(), jsProt456)
		if err457 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveDataset(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryMeta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryMeta requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.QueryMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteDataset":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteDataset requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteDataset(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getVersionHistory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetVersionHistory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetVersionHistory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "registerTransform":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "RegisterTransform requires 3 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.RegisterTransform(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "deleteFunction":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteFunction requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteFunction(context.Background(), value0))
		fmt.Print("\n")
		break
	case "listFunctions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ListFunctions requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ListFunctions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "registerUDF":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "RegisterUDF requires 4 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		fmt.Print(client.RegisterUDF(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "downloadFunction":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DownloadFunction requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DownloadFunction(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "saveTransformCompare":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveTransformCompare requires 1 args")
			flag.Usage()
		}
		arg472 := flag.Arg(1)
		mbTrans473 := thrift.NewTMemoryBufferLen(len(arg472))
		defer mbTrans473.Close()
		_, err474 := mbTrans473.WriteString(arg472)
		if err474 != nil {
			Usage()
			return
		}
		factory475 := thrift.NewTJSONProtocolFactory()
		jsProt476 := factory475.GetProtocol(mbTrans473)
		argvalue0 := api.NewTransformJobRequest()
		err477 := argvalue0.Read(context.Background(), jsProt476)
		if err477 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveTransformCompare(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryTransformCompares":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryTransformCompares requires 1 args")
			flag.Usage()
		}
		arg478 := flag.Arg(1)
		mbTrans479 := thrift.NewTMemoryBufferLen(len(arg478))
		defer mbTrans479.Close()
		_, err480 := mbTrans479.WriteString(arg478)
		if err480 != nil {
			Usage()
			return
		}
		factory481 := thrift.NewTJSONProtocolFactory()
		jsProt482 := factory481.GetProtocol(mbTrans479)
		argvalue0 := api.NewTransformJobQueryRequest()
		err483 := argvalue0.Read(context.Background(), jsProt482)
		if err483 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryTransformCompares(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countTransformCompares":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountTransformCompares requires 1 args")
			flag.Usage()
		}
		arg484 := flag.Arg(1)
		mbTrans485 := thrift.NewTMemoryBufferLen(len(arg484))
		defer mbTrans485.Close()
		_, err486 := mbTrans485.WriteString(arg484)
		if err486 != nil {
			Usage()
			return
		}
		factory487 := thrift.NewTJSONProtocolFactory()
		jsProt488 := factory487.GetProtocol(mbTrans485)
		argvalue0 := api.NewTransformJobQueryRequest()
		err489 := argvalue0.Read(context.Background(), jsProt488)
		if err489 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountTransformCompares(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTransformCompare":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTransformCompare requires 1 args")
			flag.Usage()
		}
		argvalue0, err490 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err490 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTransformCompare(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteTransformCompare":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteTransformCompare requires 1 args")
			flag.Usage()
		}
		argvalue0, err491 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err491 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteTransformCompare(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryTransformJobs":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryTransformJobs requires 1 args")
			flag.Usage()
		}
		arg492 := flag.Arg(1)
		mbTrans493 := thrift.NewTMemoryBufferLen(len(arg492))
		defer mbTrans493.Close()
		_, err494 := mbTrans493.WriteString(arg492)
		if err494 != nil {
			Usage()
			return
		}
		factory495 := thrift.NewTJSONProtocolFactory()
		jsProt496 := factory495.GetProtocol(mbTrans493)
		argvalue0 := api.NewTransformJobQueryRequest()
		err497 := argvalue0.Read(context.Background(), jsProt496)
		if err497 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryTransformJobs(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countTransformJobs":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountTransformJobs requires 1 args")
			flag.Usage()
		}
		arg498 := flag.Arg(1)
		mbTrans499 := thrift.NewTMemoryBufferLen(len(arg498))
		defer mbTrans499.Close()
		_, err500 := mbTrans499.WriteString(arg498)
		if err500 != nil {
			Usage()
			return
		}
		factory501 := thrift.NewTJSONProtocolFactory()
		jsProt502 := factory501.GetProtocol(mbTrans499)
		argvalue0 := api.NewTransformJobQueryRequest()
		err503 := argvalue0.Read(context.Background(), jsProt502)
		if err503 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountTransformJobs(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTransformJob":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTransformJob requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTransformJob(context.Background(), value0))
		fmt.Print("\n")
		break
	case "commitTransformJob":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CommitTransformJob requires 1 args")
			flag.Usage()
		}
		argvalue0, err505 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err505 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CommitTransformJob(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTransformJobStatus":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTransformJobStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTransformJobStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "cancelTransformJob":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CancelTransformJob requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.CancelTransformJob(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTransformJobBloodline":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTransformJobBloodline requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2) == "true"
		value1 := argvalue1
		fmt.Print(client.GetTransformJobBloodline(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getUserManualFile":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetUserManualFile requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetUserManualFile(context.Background()))
		fmt.Print("\n")
		break
	case "generateJavaCode":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GenerateJavaCode requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GenerateJavaCode(context.Background()))
		fmt.Print("\n")
		break
	case "generateGoCode":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GenerateGoCode requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GenerateGoCode(context.Background()))
		fmt.Print("\n")
		break
	case "generatePythonCode":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GeneratePythonCode requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GeneratePythonCode(context.Background()))
		fmt.Print("\n")
		break
	case "generateRestfulApiCode":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GenerateRestfulApiCode requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GenerateRestfulApiCode(context.Background()))
		fmt.Print("\n")
		break
	case "generateAllCode":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GenerateAllCode requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GenerateAllCode(context.Background()))
		fmt.Print("\n")
		break
	case "getGenerationStatus":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetGenerationStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetGenerationStatus(context.Background()))
		fmt.Print("\n")
		break
	case "validateThriftFile":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ValidateThriftFile requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ValidateThriftFile(context.Background()))
		fmt.Print("\n")
		break
	case "login":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Login requires 1 args")
			flag.Usage()
		}
		arg510 := flag.Arg(1)
		mbTrans511 := thrift.NewTMemoryBufferLen(len(arg510))
		defer mbTrans511.Close()
		_, err512 := mbTrans511.WriteString(arg510)
		if err512 != nil {
			Usage()
			return
		}
		factory513 := thrift.NewTJSONProtocolFactory()
		jsProt514 := factory513.GetProtocol(mbTrans511)
		argvalue0 := api.NewLoginRequest()
		err515 := argvalue0.Read(context.Background(), jsProt514)
		if err515 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Login(context.Background(), value0))
		fmt.Print("\n")
		break
	case "refreshToken":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RefreshToken requires 1 args")
			flag.Usage()
		}
		arg516 := flag.Arg(1)
		mbTrans517 := thrift.NewTMemoryBufferLen(len(arg516))
		defer mbTrans517.Close()
		_, err518 := mbTrans517.WriteString(arg516)
		if err518 != nil {
			Usage()
			return
		}
		factory519 := thrift.NewTJSONProtocolFactory()
		jsProt520 := factory519.GetProtocol(mbTrans517)
		argvalue0 := api.NewRefreshTokenRequest()
		err521 := argvalue0.Read(context.Background(), jsProt520)
		if err521 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RefreshToken(context.Background(), value0))
		fmt.Print("\n")
		break
	case "verifyToken":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "VerifyToken requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.VerifyToken(context.Background()))
		fmt.Print("\n")
		break
	case "logout":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "Logout requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.Logout(context.Background()))
		fmt.Print("\n")
		break
	case "getCurrentAuthUser":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCurrentAuthUser requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCurrentAuthUser(context.Background()))
		fmt.Print("\n")
		break
	case "saveUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveUser requires 1 args")
			flag.Usage()
		}
		arg522 := flag.Arg(1)
		mbTrans523 := thrift.NewTMemoryBufferLen(len(arg522))
		defer mbTrans523.Close()
		_, err524 := mbTrans523.WriteString(arg522)
		if err524 != nil {
			Usage()
			return
		}
		factory525 := thrift.NewTJSONProtocolFactory()
		jsProt526 := factory525.GetProtocol(mbTrans523)
		argvalue0 := api.NewUserEntity()
		err527 := argvalue0.Read(context.Background(), jsProt526)
		if err527 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryUsers":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryUsers requires 1 args")
			flag.Usage()
		}
		arg528 := flag.Arg(1)
		mbTrans529 := thrift.NewTMemoryBufferLen(len(arg528))
		defer mbTrans529.Close()
		_, err530 := mbTrans529.WriteString(arg528)
		if err530 != nil {
			Usage()
			return
		}
		factory531 := thrift.NewTJSONProtocolFactory()
		jsProt532 := factory531.GetProtocol(mbTrans529)
		argvalue0 := api.NewUserQueryRequest()
		err533 := argvalue0.Read(context.Background(), jsProt532)
		if err533 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countUsers":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountUsers requires 1 args")
			flag.Usage()
		}
		arg534 := flag.Arg(1)
		mbTrans535 := thrift.NewTMemoryBufferLen(len(arg534))
		defer mbTrans535.Close()
		_, err536 := mbTrans535.WriteString(arg534)
		if err536 != nil {
			Usage()
			return
		}
		factory537 := thrift.NewTJSONProtocolFactory()
		jsProt538 := factory537.GetProtocol(mbTrans535)
		argvalue0 := api.NewUserQueryRequest()
		err539 := argvalue0.Read(context.Background(), jsProt538)
		if err539 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "allUsers":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "AllUsers requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.AllUsers(context.Background()))
		fmt.Print("\n")
		break
	case "queryUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryUser requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.QueryUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteUser requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "updateUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateUser requires 1 args")
			flag.Usage()
		}
		arg542 := flag.Arg(1)
		mbTrans543 := thrift.NewTMemoryBufferLen(len(arg542))
		defer mbTrans543.Close()
		_, err544 := mbTrans543.WriteString(arg542)
		if err544 != nil {
			Usage()
			return
		}
		factory545 := thrift.NewTJSONProtocolFactory()
		jsProt546 := factory545.GetProtocol(mbTrans543)
		argvalue0 := api.NewUserEntity()
		err547 := argvalue0.Read(context.Background(), jsProt546)
		if err547 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getRoles":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetRoles requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetRoles(context.Background()))
		fmt.Print("\n")
		break
	case "changePassword":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ChangePassword requires 1 args")
			flag.Usage()
		}
		arg548 := flag.Arg(1)
		mbTrans549 := thrift.NewTMemoryBufferLen(len(arg548))
		defer mbTrans549.Close()
		_, err550 := mbTrans549.WriteString(arg548)
		if err550 != nil {
			Usage()
			return
		}
		factory551 := thrift.NewTJSONProtocolFactory()
		jsProt552 := factory551.GetProtocol(mbTrans549)
		argvalue0 := api.NewChangePasswordRequest()
		err553 := argvalue0.Read(context.Background(), jsProt552)
		if err553 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ChangePassword(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getCurrentUser":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCurrentUser requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCurrentUser(context.Background()))
		fmt.Print("\n")
		break
	case "listOwnerTables":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ListOwnerTables requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListOwnerTables(context.Background()))
		fmt.Print("\n")
		break
	case "queryDataPermissions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryDataPermissions requires 1 args")
			flag.Usage()
		}
		arg554 := flag.Arg(1)
		mbTrans555 := thrift.NewTMemoryBufferLen(len(arg554))
		defer mbTrans555.Close()
		_, err556 := mbTrans555.WriteString(arg554)
		if err556 != nil {
			Usage()
			return
		}
		factory557 := thrift.NewTJSONProtocolFactory()
		jsProt558 := factory557.GetProtocol(mbTrans555)
		argvalue0 := api.NewDataPermissionQueryRequest()
		err559 := argvalue0.Read(context.Background(), jsProt558)
		if err559 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryDataPermissions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countDataPermissions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountDataPermissions requires 1 args")
			flag.Usage()
		}
		arg560 := flag.Arg(1)
		mbTrans561 := thrift.NewTMemoryBufferLen(len(arg560))
		defer mbTrans561.Close()
		_, err562 := mbTrans561.WriteString(arg560)
		if err562 != nil {
			Usage()
			return
		}
		factory563 := thrift.NewTJSONProtocolFactory()
		jsProt564 := factory563.GetProtocol(mbTrans561)
		argvalue0 := api.NewDataPermissionQueryRequest()
		err565 := argvalue0.Read(context.Background(), jsProt564)
		if err565 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountDataPermissions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "updateDataPermission":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDataPermission requires 1 args")
			flag.Usage()
		}
		arg566 := flag.Arg(1)
		mbTrans567 := thrift.NewTMemoryBufferLen(len(arg566))
		defer mbTrans567.Close()
		_, err568 := mbTrans567.WriteString(arg566)
		if err568 != nil {
			Usage()
			return
		}
		factory569 := thrift.NewTJSONProtocolFactory()
		jsProt570 := factory569.GetProtocol(mbTrans567)
		argvalue0 := api.NewDataPermissionUpdateRequest()
		err571 := argvalue0.Read(context.Background(), jsProt570)
		if err571 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateDataPermission(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
